#!/usr/bin/env python3
"""Read/write the editable dialogue source (.gmm XML) behind a message symbol.

A message symbol like `msg_0553_T21R0301_00000` maps to:
  file : files/msgdata/msg/msg_0553_T21R0301.gmm
  row  : <row id="msg_0553_T21R0301_00000"> ... <language name="English">TEXT</language>

The .h headers are autogenerated (DO NOT MODIFY); the .gmm is the source `make`
recompiles, so edits here survive a build.  We edit with a targeted regex so the
rest of the file (indentation, other rows, attributes) stays byte-for-byte intact.
"""
from __future__ import annotations

import functools
import re
from pathlib import Path

DECOMP = Path(__file__).resolve().parents[2] / "disasm" / "pokeheartgold"
MSG_DIR = DECOMP / "files" / "msgdata" / "msg"


def gmm_path(sym: str) -> Path:
    return MSG_DIR / (sym.rsplit("_", 1)[0] + ".gmm")


@functools.lru_cache(maxsize=600)
def _read(path_str: str) -> str | None:
    p = Path(path_str)
    return p.read_text(encoding="utf-8") if p.exists() else None


def _row_re(sym: str) -> re.Pattern:
    return re.compile(
        r'(<row id="' + re.escape(sym) + r'"[^>]*>.*?<language name="English">)'
        r'(.*?)(</language>)', re.S)


def _unescape(s: str) -> str:
    return (s.replace("&amp;", "&").replace("&lt;", "<")
             .replace("&gt;", ">").replace("&quot;", '"').replace("&apos;", "'"))


def _escape(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def get_text(sym: str) -> str | None:
    """Raw source text for a message symbol (keeps \\n soft-wrap / \\r page codes)."""
    src = _read(str(gmm_path(sym)))
    if src is None:
        return None
    m = _row_re(sym).search(src)
    return _unescape(m.group(2)) if m else None


def set_text(sym: str, text: str) -> bool:
    """Overwrite a message's English text in its .gmm source. Returns True on hit."""
    p = gmm_path(sym)
    src = _read(str(p))
    if src is None:
        return False
    new, n = _row_re(sym).subn(
        lambda m: m.group(1) + _escape(text) + m.group(3), src)
    if n:
        p.write_text(new, encoding="utf-8")
        _read.cache_clear()          # file changed on disk; drop stale copies
    return bool(n)
