#!/usr/bin/env python3
"""Headless mGBA acceptance checks for Route 29 and Route 30 (each phase a fresh emulator process).

  write  new game in Cherrygrove; walk east into Route 29 and north into Route 30 across the real map
         connections and back; one-way ledges (jump down, blocked from below); ledge walls, rock walls,
         railing, pond and the closed Route 46 gate block; both routes' signs; the hidden Potion (flag set
         once, and the tile then holds nothing); tall grass with an empty party starts no battle; walk the
         full length of each route; camera views for review; ordinary save at the Route 29 lookout
  read   cold flash reload of that save
  menu   title screen -> Continue from a cold boot

    python3 tools/gba/maps/claude_routes/runtime.py tools/vendor/gba/claude-routes tools/vendor/gba/routes-check-NN
"""
from __future__ import annotations
import json, os, shlex, subprocess, sys
from pathlib import Path
from PIL import Image

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
from claude_routes import layouts as L  # noqa: E402

ROOT = HERE.parents[3]
import platform as _platform
_TOOLCHAINS = {'Linux-x86_64': 'arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi', 'Linux-aarch64': 'arm-gnu-toolchain-14.2.rel1-aarch64-arm-none-eabi', 'Darwin-arm64': 'arm-gnu-toolchain-14.2.rel1-darwin-arm64-arm-none-eabi'}
TOOLCHAIN = ROOT / 'tools/vendor/gba' / _TOOLCHAINS[_platform.system() + '-' + _platform.machine()]
TOWN, R29, R30 = 0, 9, 10
A, B, RIGHT, LEFT, UP, DOWN = 1, 2, 16, 32, 64, 128
SAVE_AT = (58, 26)

TEMPLATE = r'''
// Generated by claude_routes/runtime.py: Route 29 and Route 30 acceptance.
#define main unused_map_qualification_main
#include "RUNTIME_C"
#undef main
static const char *out;
static int fails;
static void shot(const char*t){screenshot(out,t);}
static void go(unsigned map,unsigned x,unsigned y){call("MapProof_Enter",map|(x<<8)|(y<<16));frames(360,0);}
static void need(int ok,const char*tag){if(!ok){fprintf(stderr,"FAILED %s (map %u at %u,%u)\n",tag,state[2],state[3],state[4]);shot(tag);exit(40);}}
static void at(unsigned map,unsigned x,unsigned y,const char*tag){observe(tag);need(state[1]==80&&state[2]==map&&state[3]==x&&state[4]==y,tag);}
static void pos(unsigned*m,unsigned*x,unsigned*y){call("MapProof_ReadState",0);unsigned a=sym("gMapProofState");*m=c->busRead32(c,a+8);*x=c->busRead32(c,a+12);*y=c->busRead32(c,a+16);}
// One tile per iteration: hold the direction until the player's destination changes (a turn, a map connection or a
// ledge can take extra frames), give up after 64 frames when something blocks, then let the movement finish.
static void step(unsigned key,int n){for(int i=0;i<n;i++){unsigned m0,x0,y0,m1,x1,y1;pos(&m0,&x0,&y0);int moved=0;for(int t=0;t<32&&!moved;t++){frames(2,key);pos(&m1,&x1,&y1);moved=(m1!=m0||x1!=x0||y1!=y0);}frames(moved?40:8,0);}frames(16,0);}
static void tap(unsigned key){frames(2,key);frames(12,0);}
static int locked(void){return call("ArePlayerFieldControlsLocked",0);}
static int overworld(void){unsigned cb=c->busRead32(c,sym("gMain")+4);return (cb&~1u)==(sym("CB2_Overworld")&~1u);}
static void close_dialog(void){for(int i=0;i<40&&locked();i++){frames(1,B);frames(40,0);}need(!locked(),"dialogue-closes");}
static void read_sign(unsigned map,unsigned x,unsigned y,const char*tag){go(map,x,y+1);tap(UP);frames(1,A);frames(120,0);need(locked(),tag);shot(tag);close_dialog();}
int main(int argc,char**argv){
 if(argc!=5){fprintf(stderr,"runtime ROM SYMBOLS OUT write|read|menu\n");return 2;}
 out=argv[3];FILE*f=fopen(argv[2],"r");if(!f)return 3;while(ns<128&&fscanf(f,"%79s %x",names[ns],&addrs[ns])==2)ns++;fclose(f);
 struct mLogger log={.log=quiet};mLogSetDefaultLogger(&log);c=mCoreFind(argv[1]);if(!c||!c->init(c))return 4;mCoreConfigInit(&c->config,"claude-routes");c->setVideoBuffer(c,pixels,240);if(!mCoreLoadFile(c,argv[1]))return 5;
 char flash[2048];snprintf(flash,sizeof(flash),"%s/routes.sav",argv[3]);
 if(!strcmp(argv[4],"read")||!strcmp(argv[4],"menu")){unsigned char data[131072];f=fopen(flash,"rb");if(!f||fread(data,1,sizeof(data),f)!=sizeof(data))return 6;fclose(f);if(!c->savedataRestore(c,data,sizeof(data),false))return 7;}
 c->rtc.override=RTC_FIXED;c->rtc.value=1789315200000LL;
 c->reset(c);frames(600,0);
 if(!strcmp(argv[4],"menu")){
  frames(1,8);frames(180,0);frames(1,A);frames(300,0);frames(1,A);frames(180,0);shot("continue-menu");frames(1,A);frames(300,0);shot("title-continue");at(R29,SAVE_X,SAVE_Y,"title-continue");
 }else if(!strcmp(argv[4],"read")){
  unsigned s=call("LoadGameSave",0);need(s==1,"load-status");call("MapProof_Resume",0);frames(240,0);shot("cold-reload");at(R29,SAVE_X,SAVE_Y,"cold-reload");
  need(call("FlagGet",HIDDEN_FLAG)==1,"potion-flag-survives-save");
 }else{
  call("MapProof_Boot",0);frames(240,0);observe("new-game");
  // The map-proof boot skips naming; give the player a name so messages that print it terminate.
  {static const unsigned char nm[]={0xCA,0xC6,0xBB,0xD3,0xBF,0xCC,0xFF,0xFF};unsigned sb2=c->busRead32(c,sym("gSaveBlock2Ptr"));for(int i=0;i<8;i++)c->busWrite8(c,sb2+i,nm[i]);}need(call("CalculatePlayerPartyCount",0)==0,"empty-party");
  // Cherrygrove -> Route 29 across the east connection, and back.
  go(TOWN,TOWN_EAST_X-3,TOWN_EAST_Y);step(RIGHT,3);at(TOWN,TOWN_EAST_X,TOWN_EAST_Y,"town-east-edge");shot("seam-town-east");
  step(RIGHT,1);at(R29,0,TOWN_EAST_Y+R29_ROWS,"enter-route29");shot("cross29-in-0");
  for(int i=1;i<=8;i++){char t[40];step(RIGHT,1);sprintf(t,"cross29-in-%d",i);shot(t);}
  step(LEFT,8);at(R29,0,TOWN_EAST_Y+R29_ROWS,"route29-west-edge");
  step(LEFT,1);at(TOWN,TOWN_EAST_X,TOWN_EAST_Y,"back-to-town-from-29");shot("cross29-out-0");
  for(int i=1;i<=8;i++){char t[40];step(LEFT,1);sprintf(t,"cross29-out-%d",i);shot(t);}
  // Route 29 end to end along the main path, to the New Bark edge (no map beyond it yet).
  go(R29,0,17);
  SHOTS29
  go(R29,90,16);step(RIGHT,7);at(R29,97,16,"route29-east-edge");step(RIGHT,2);at(R29,97,16,"route29-east-edge-holds");shot("route29-east-end");
  // Ledges: jump down, blocked from below; ledge walls; the closed gate; the railing.
  go(R29,17,13);step(DOWN,1);at(R29,17,15,"ledge-jump-29a");step(UP,1);at(R29,17,15,"ledge-blocks-from-below-29a");
  go(R29,24,17);step(DOWN,1);at(R29,24,19,"ledge-jump-29b");
  go(R29,33,21);step(DOWN,1);at(R29,33,23,"ledge-jump-29c");
  go(R29,27,12);step(RIGHT,1);at(R29,27,12,"ledge-wall-blocks-29");
  go(R29,14,16);step(LEFT,1);at(R29,14,16,"ledge-wall-blocks-29-west");
  go(R29,52,9);step(UP,1);at(R29,52,9,"gate-closed");shot("route46-gate");
  go(R29,58,26);step(DOWN,1);at(R29,58,26,"railing-blocks");shot("lookout");
  // Tall grass with an empty party: twelve steps through two blocks, still in the field.
  go(R29,18,16);for(int i=0;i<6;i++){step(RIGHT,1);need(overworld()&&!locked(),"grass-29-no-battle");}
  go(R30,15,64);for(int i=0;i<6;i++){step(RIGHT,1);need(overworld()&&!locked(),"grass-30-no-battle");}
  printf("{\"tall_grass_steps_without_battle\":12}\n");
  // Signs.
  read_sign(R29,6,14,"sign-route29-west");read_sign(R29,87,14,"sign-route29-east");
  read_sign(R30,20,34,"sign-route30-junction");read_sign(R30,13,58,"sign-route30-south");
  // The hidden Potion at the lookout: found once.
  need(call("FlagGet",HIDDEN_FLAG)==0,"potion-flag-clear");
  go(R29,POTION_X-1,POTION_Y);tap(RIGHT);frames(1,A);frames(150,0);need(locked(),"potion-found");shot("potion-found");close_dialog();
  need(call("FlagGet",HIDDEN_FLAG)==1,"potion-flag-set");
  go(R29,POTION_X-1,POTION_Y);tap(RIGHT);frames(1,A);frames(90,0);int again=locked();if(again)close_dialog();need(!again,"potion-only-once");
  printf("{\"hidden_potion\":\"found once\",\"flag\":%u}\n",HIDDEN_FLAG);
  // Cherrygrove -> Route 30 across the north connection, and back.
  go(TOWN,TOWN_NORTH_X,3);step(UP,3);at(TOWN,TOWN_NORTH_X,0,"town-north-edge");shot("seam-town-north");
  step(UP,1);at(R30,TOWN_NORTH_X-R30_COLS,R30_H-1,"enter-route30");shot("cross30-in-0");
  for(int i=1;i<=7;i++){char t[40];step(UP,1);sprintf(t,"cross30-in-%d",i);shot(t);}
  step(DOWN,7);at(R30,TOWN_NORTH_X-R30_COLS,R30_H-1,"route30-south-edge");
  step(DOWN,1);at(TOWN,TOWN_NORTH_X,0,"back-to-town-from-30");shot("cross30-out-0");
  for(int i=1;i<=8;i++){char t[40];step(DOWN,1);sprintf(t,"cross30-out-%d",i);shot(t);}
  // Route 30 up the main path: ledges are one-way south, the steps climb the rock bands.
  go(R30,8,64);step(DOWN,1);at(R30,8,66,"ledge-jump-30-low");step(UP,1);at(R30,8,66,"ledge-blocks-from-below-30");
  go(R30,8,64);step(UP,2);at(R30,8,62,"low-steps");
  go(R30,10,30);step(UP,2);at(R30,10,28,"middle-steps");step(UP,1);at(R30,10,27,"middle-steps-top");
  go(R30,10,2);step(UP,2);at(R30,10,0,"top-steps");shot("route30-top-steps");
  go(R30,10,2);step(DOWN,1);at(R30,10,4,"ledge-jump-30-top");
  go(R30,10,11);step(DOWN,1);at(R30,10,13,"ledge-jump-30-north");
  go(R30,20,52);step(RIGHT,1);at(R30,20,52,"pond-blocks");
  go(R30,7,40);step(LEFT,2);at(R30,7,40,"west-woods-block");
  go(R30,31,20);step(RIGHT,2);at(R30,31,20,"east-cliff-blocks");
  go(R30,27,9);step(UP,4);at(R30,27,6,"mr-pokemon-doorstep");shot("mr-pokemon-house");
  SHOTS30
  // Save at the lookout for the cold-reload and Continue phases.
  go(R29,SAVE_X,SAVE_Y);at(R29,SAVE_X,SAVE_Y,"save-at-lookout");
  unsigned status=call("TrySavingData",0);void*data=NULL;size_t size=c->savedataClone(c,&data);f=fopen(flash,"wb");if(status!=1||size!=131072||!f||fwrite(data,1,size,f)!=size)return 11;fclose(f);free(data);printf("{\"save_status\":%u,\"flash_bytes\":%zu}\n",status,size);
 }
 c->deinit(c);return 0;
}
'''

SHOTS29 = [('r29-view-west', 6, 16), ('r29-view-lawn', 22, 12), ('r29-view-centre', 40, 18), ('r29-view-gate', 52, 12),
           ('r29-view-south', 52, 24), ('r29-view-lookout', 58, 25), ('r29-view-east-grass', 75, 18), ('r29-view-east', 90, 16)]
SHOTS30 = [('r30-view-south', 8, 68), ('r30-view-berry-house', 12, 56), ('r30-view-pond', 18, 52), ('r30-view-junction', 18, 37),
           ('r30-view-middle', 10, 30), ('r30-view-corridor', 10, 16), ('r30-view-plateau', 24, 9), ('r30-view-north', 10, 3)]

def generate():
    from claude_cherrygrove import layout as TL
    src = TEMPLATE.replace('RUNTIME_C', str(ROOT / 'tools/gba/maps/runtime.c'))
    rep = dict(TOWN_EAST_X=TL.W - 1, TOWN_EAST_Y=TL.EAST_EXIT[0] + 1, R29_ROWS=-L.R29_TOWN_OFFSET, TOWN_NORTH_X=TL.NORTH_EXIT[0] + 1,
               R30_COLS=L.R30_TOWN_OFFSET, R30_H=L.R30_H, POTION_X=L.R29_HIDDEN_POTION[0], POTION_Y=L.R29_HIDDEN_POTION[1],
               SAVE_X=SAVE_AT[0], SAVE_Y=SAVE_AT[1], HIDDEN_FLAG=0x264,
               TOWN=TOWN, R29=R29, R30=R30, RIGHT=RIGHT, LEFT=LEFT, UP=UP, DOWN=DOWN)
    src = src.replace('SHOTS29', ''.join(f'go(R29,{x},{y});shot("{t}");' for t, x, y in SHOTS29))
    src = src.replace('SHOTS30', ''.join(f'go(R30,{x},{y});shot("{t}");' for t, x, y in SHOTS30))
    defines = ''.join(f'#define {k} {v}\n' for k, v in rep.items()) + '#define A 1\n#define B 2\n'
    return src.replace('#undef main\n', '#undef main\n' + defines, 1)

def main():
    game = Path(sys.argv[1]).resolve(); out = Path(sys.argv[2]).resolve(); out.mkdir(parents=True, exist_ok=False)
    src = generate(); csrc = out / 'routes_runtime.c'; csrc.write_text(src)
    (HERE / 'generated').mkdir(exist_ok=True); (HERE / 'generated' / 'routes_runtime.c').write_text(src)
    flags = shlex.split(os.environ.get('MGBA_FLAGS', ''))
    if not flags and Path('/opt/homebrew/opt/mgba').exists(): flags = ['-I/opt/homebrew/opt/mgba/include', '-L/opt/homebrew/opt/mgba/lib', '-lmgba']
    if not flags: flags = ['-lmgba']
    subprocess.run(['cc', str(csrc), *flags, '-o', str(out / 'runtime')], check=True)
    lines = subprocess.check_output([str(TOOLCHAIN / 'bin/arm-none-eabi-nm'), str(game / 'pokeemerald.elf')], text=True)
    wanted = {'MapProof_Boot', 'MapProof_Enter', 'MapProof_ReadState', 'MapProof_Resume', 'gMapProofState', 'TrySavingData', 'LoadGameSave',
              'ArePlayerFieldControlsLocked', 'FlagGet', 'CalculatePlayerPartyCount', 'gMain', 'CB2_Overworld', 'gSaveBlock2Ptr'}
    symbols = {r[2]: r[0] for l in lines.splitlines() if len(r := l.split()) == 3 and r[2] in wanted}; assert symbols.keys() == wanted, wanted - symbols.keys()
    (out / 'symbols.txt').write_text(''.join(f'{k} {v}\n' for k, v in symbols.items()))
    results = []
    for phase in (sys.argv[3:] or ['write', 'read', 'menu']):
        r = subprocess.run([str(out / 'runtime'), str(game / 'pokeemerald.gba'), str(out / 'symbols.txt'), str(out), phase], capture_output=True, text=True, timeout=1800)
        (out / (phase + '.jsonl')).write_text(r.stdout)
        results.append(dict(phase=phase, exit_code=r.returncode, stderr=r.stderr, observations=[json.loads(l) for l in r.stdout.splitlines() if l.startswith('{')]))
        (out / 'results.json').write_text(json.dumps(results, indent=2) + '\n')
        for file in out.glob('*.ppm'):
            Image.open(file).save(file.with_suffix('.png')); file.unlink()
        print(phase, r.returncode, r.stderr[-600:], flush=True)
        if r.returncode != 0: sys.exit(r.returncode)
    print('All phases passed.')

if __name__ == '__main__':
    main()
