#!/usr/bin/env python3
"""Generate and run the headless mGBA acceptance checks for the Claude Cherrygrove build.

Phases (each a fresh emulator process):
  write  new game at the front door, every door in and out, bedroom stairs, both
         route connections and back, shoreline collision, Mart menu, ordinary save
  read   cold flash reload of that save, ordinary LoadGameSave
  menu   real title screen -> Continue from a cold boot
  walk   NPC observation: 5 camera views x 360 samples of every resident, actual
         OBJ VRAM frames compared with the source cells, one conversation per cast
         member and visitor (stop, face player, resume)

    python3 tools/gba/maps/claude_cherrygrove/runtime.py tools/vendor/gba/claude-cherrygrove tools/vendor/gba/claude-check-NN
"""
from __future__ import annotations
import json, os, shlex, shutil, subprocess, sys
from pathlib import Path
from PIL import Image

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
from claude_cherrygrove import layout as L, cast  # noqa: E402

ROOT = HERE.parents[3]
import platform as _platform
_TOOLCHAINS = {'Linux-x86_64': 'arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi', 'Linux-aarch64': 'arm-gnu-toolchain-14.2.rel1-aarch64-arm-none-eabi', 'Darwin-arm64': 'arm-gnu-toolchain-14.2.rel1-darwin-arm64-arm-none-eabi'}
TOOLCHAIN = ROOT / 'tools/vendor/gba' / _TOOLCHAINS[_platform.system() + '-' + _platform.machine()]

MAP_INDEX = {'CherrygroveCity': 0, 'PlayerHouse': 1, 'GoldHouse': 2, 'NeighborHouse': 3, 'TransplantHouse': 4, 'Mart': 5, 'PokemonCenter': 6,
             'PlayerBedroom': 7, 'CenterUpstairs': 8, 'Route29Approach': 9, 'Route30Approach': 10}
# Interior exit warps (x, y) inside each donor interior, from the workbench map.json files.
EXITS = {'PlayerHouse': (9, 8), 'GoldHouse': (3, 8), 'NeighborHouse': (3, 8), 'TransplantHouse': (3, 8), 'Mart': (3, 7), 'PokemonCenter': (7, 8)}

TEMPLATE = r'''
// Generated by runtime.py: town acceptance for the Claude Cherrygrove exterior.
#define main unused_map_qualification_main
#include "RUNTIME_C"
#undef main
static void close_dialog(void){for(int i=0;i<40 && call("ArePlayerFieldControlsLocked",0);i++){frames(1,2);frames(40,0);}if(call("ArePlayerFieldControlsLocked",0)){fprintf(stderr,"field still locked after dialogue\n");exit(45);}}
static void go(unsigned map,unsigned x,unsigned y){call("MapProof_Enter",map|(x<<8)|(y<<16));frames(360,0);}
static void expect(unsigned map,const char*tag){observe(tag);if(state[0]!=2||state[1]!=80||state[2]!=map){fprintf(stderr,"expected town group 80 map %u at %s (got %u/%u/%u)\n",map,tag,state[0],state[1],state[2]);exit(40);}}
static int visible_frame(unsigned sprite){
 unsigned vram=0x06010000+(c->busRead16(c,sprite+4)&1023)*32;
 unsigned images=c->busRead32(c,sprite+0xc);
 for(int f=0;f<12;f++){
  unsigned data=c->busRead8(c,images+6) ? c->busRead32(c,images)+f*c->busRead16(c,images+4) : c->busRead32(c,images+f*8);int same=1;
  for(unsigned i=0;i<512;i+=4)if(c->busRead32(c,vram+i)!=c->busRead32(c,data+i)){same=0;break;}
  if(same)return f;
 }
 return -1;
}
static unsigned view;
static void sample(unsigned tick){
 printf("{\"view\":%u,\"tick\":%u,\"objects\":[",view,tick);int comma=0;
 for(unsigned i=0;i<16;i++){
  unsigned o=sym("gObjectEvents")+i*0x24;
  if(!(c->busRead8(c,o)&1))continue;
  unsigned gid=c->busRead16(c,o+4),sid=c->busRead8(c,o+0x23),s=sym("gSprites")+sid*0x44;
  if(gid<1024||gid>=1037||gid==1028)continue;
  printf("%s{\"gfx\":%u,\"local\":%u,\"x\":%d,\"y\":%d,\"facing\":%u,\"anim\":%u,\"palette\":%u,\"hflip\":%u,\"frame\":%d}",comma++?",":"",gid,c->busRead8(c,o+8),(short)c->busRead16(c,o+0x10)-7,(short)c->busRead16(c,o+0x12)-7,c->busRead8(c,o+0x18)&15,c->busRead8(c,s+0x2a),c->busRead16(c,s+4)>>12,c->busRead8(c,s+0x3f)&1,visible_frame(s));
 }
 printf("]}\n");
}
static const char *argv_out;
static void interaction(unsigned gid,unsigned x,unsigned y,unsigned key,const char *tag){
 // A warp reloads the map, so the NPC is back on its spawn cell; press A quickly before it wanders.
 int locked=0;
 for(int attempt=0;attempt<12&&!locked;attempt++){
  call("MapProof_Enter",(x<<8)|(y<<16));frames(70,0);
  frames(1,key);frames(6,0);
  for(unsigned i=0;i<10&&!call("ArePlayerFieldControlsLocked",0);i++){frames(2,1);frames(6,0);}
  locked=call("ArePlayerFieldControlsLocked",0);
 }
 if(!locked){screenshot(argv_out,"interaction-failed");fprintf(stderr,"Could not interact with %u\n",gid);exit(31);}
 frames(180,0);screenshot(argv_out,tag);
 unsigned o=0;for(unsigned i=0;i<16;i++){unsigned q=sym("gObjectEvents")+i*0x24;if((c->busRead8(c,q)&1)&&c->busRead16(c,q+4)==gid)o=q;}
 if(!o){fprintf(stderr,"npc %u not loaded\n",gid);exit(32);}
 unsigned facing=c->busRead8(c,o+0x18)&15; unsigned sprite=sym("gSprites")+c->busRead8(c,o+0x23)*0x44; int fr=visible_frame(sprite);
 static const int idle[5]={-1,9,0,1,4};
 if(fr!=idle[facing]){fprintf(stderr,"NPC %u facing %u displays frame %d\n",gid,facing,fr);exit(36);}
 unsigned pos=c->busRead32(c,o+0x10);
 frames(120,0);if(c->busRead32(c,o+0x10)!=pos)exit(33);
 for(unsigned i=0;i<40&&call("ArePlayerFieldControlsLocked",0);i++){frames(1,2);frames(40,0);}
 if(call("ArePlayerFieldControlsLocked",0))exit(34);
 printf("{\"interaction\":%u,\"faces_player\":%u,\"displayed_idle_frame_verified\":true,\"stops_for_dialogue\":true}\n",gid,facing);
}
int main(int argc,char**argv){
 if(argc!=5){fprintf(stderr,"runtime ROM SYMBOLS OUT write|read|menu|walk\n");return 2;}
 argv_out=argv[3];FILE*f=fopen(argv[2],"r");if(!f)return 3;while(ns<128&&fscanf(f,"%79s %x",names[ns],&addrs[ns])==2)ns++;fclose(f);
 struct mLogger log={.log=quiet};mLogSetDefaultLogger(&log);c=mCoreFind(argv[1]);if(!c||!c->init(c))return 4;mCoreConfigInit(&c->config,"claude-cherrygrove");c->setVideoBuffer(c,pixels,240);if(!mCoreLoadFile(c,argv[1]))return 5;
 char flash[2048];snprintf(flash,sizeof(flash),"%s/town.sav",argv[3]);
 if(!strcmp(argv[4],"read")||!strcmp(argv[4],"menu")){unsigned char data[131072];f=fopen(flash,"rb");if(!f||fread(data,1,sizeof(data),f)!=sizeof(data))return 6;fclose(f);if(!c->savedataRestore(c,data,sizeof(data),false))return 7;}
 c->rtc.override=RTC_FIXED;c->rtc.value=1789315200000LL;
 c->reset(c);frames(600,0);
 if(!strcmp(argv[4],"menu")){
  screenshot(argv[3],"boot-before-start");frames(1,8);frames(180,0);screenshot(argv[3],"boot-after-start");frames(1,1);frames(300,0);screenshot(argv[3],"boot-after-a");frames(1,1);frames(180,0);screenshot(argv[3],"continue-menu");frames(1,1);frames(300,0);screenshot(argv[3],"ordinary-continue");expect(0,"ordinary-title-continue");if(state[3]!=SPAWN_X||state[4]!=SPAWN_Y)return 12;
 }else if(!strcmp(argv[4],"read")){
  unsigned s=call("LoadGameSave",0);if(s!=1)return 8;call("MapProof_Resume",0);frames(240,0);expect(0,"cold-reload");screenshot(argv[3],"cold-reload");if(state[3]!=SPAWN_X||state[4]!=SPAWN_Y)return 9;
 }else if(!strcmp(argv[4],"walk")){
  call("MapProof_Boot",0);frames(240,0);
  const unsigned views[][2]={VIEWS};
  for(view=0;view<NVIEWS;view++){
   call("MapProof_Enter",(views[view][0]<<8)|(views[view][1]<<16));frames(360,0);
   for(unsigned i=0;i<360;i++){frames(4,0);sample(i*4);if(view<4){char tag[80];sprintf(tag,"view-%u-%03u",view,i);screenshot(argv[3],tag);}}
  }
  INTERACTIONS
 }else{
  call("MapProof_Boot",0);frames(240,0);expect(0,"town-spawn");screenshot(argv[3],"town-spawn");if(state[3]!=SPAWN_X||state[4]!=SPAWN_Y){fprintf(stderr,"spawn %u,%u\n",state[3],state[4]);return 13;}
  const unsigned doors[][2]={DOORS};
  const unsigned maps[]={DOOR_MAPS};
  const unsigned exits[][2]={EXITS};
  for(unsigned i=0;i<NDOORS;i++){
   go(0,doors[i][0],doors[i][1]+1);
   for(unsigned t=0;t<100;t++){frames(1,t<20?64:0);if(t%2==0){char tag[80];sprintf(tag,"door-%u-%03u",i,t);screenshot(argv[3],tag);}}
   frames(120,0);char tag[80];sprintf(tag,"door-in-%u",maps[i]);expect(maps[i],tag);screenshot(argv[3],tag);
   go(maps[i],exits[i][0],exits[i][1]-1);frames(20,128);frames(180,0);sprintf(tag,"door-out-%u",maps[i]);expect(0,tag);
  }
  go(1,8,3);frames(20,64);frames(180,0);expect(7,"bedroom-stairs-up");screenshot(argv[3],"bedroom");
  go(7,6,1);frames(20,16);frames(180,0);expect(1,"bedroom-stairs-down");
  go(0,EAST_X,EAST_Y);frames(64,16);frames(40,0);expect(9,"route29-out");screenshot(argv[3],"route29");frames(80,32);frames(40,0);expect(0,"route29-return");
  go(0,NORTH_X,NORTH_Y);frames(64,64);frames(40,0);expect(10,"route30-out");screenshot(argv[3],"route30");frames(80,128);frames(40,0);expect(0,"route30-return");
  go(0,SHORE_X,SHORE_Y);frames(32,32);frames(20,0);expect(0,"shore-collision");if(state[3]<SHORE_MIN){fprintf(stderr,"walked into the sea: x=%u\n",state[3]);return 10;}
  SHOTS
  go(5,3,3);frames(8,32);frames(8,0);frames(1,1);frames(150,0);frames(1,1);frames(90,0);screenshot(argv[3],"mart-menu");close_dialog();
  go(0,SPAWN_X,SPAWN_Y);expect(0,"save-at-home");screenshot(argv[3],"home");unsigned status=call("TrySavingData",0);void*data=NULL;size_t size=c->savedataClone(c,&data);f=fopen(flash,"wb");if(status!=1||size!=131072||!f||fwrite(data,1,size,f)!=size)return 11;fclose(f);free(data);printf("{\"save_status\":%u,\"flash_bytes\":%zu}\n",status,size);
 }
 c->deinit(c);return 0;
}
'''

def generate():
    doors = [b for b in L.BUILDINGS]
    order = ['PlayerHouse', 'GoldHouse', 'NeighborHouse', 'TransplantHouse', 'Mart', 'PokemonCenter']
    by = {b['name']: b for b in doors}
    door_cells = [L.door_of(by[n]) for n in order]
    views = [(50, 18), (40, 9), (44, 14), (43, 25), (24, 20), (19, 27), (21, 9)]
    shots = [('home-street', 50, 18), ('shops', 40, 9), ('gold-yard', 44, 14), ('park', 43, 25), ('beach', 24, 20), ('pier', 21, 26), ('lookout', 19, 6), ('cliff', 10, 5)]
    gid = {'OBJ_EVENT_GFX_JOHTO_GOLD': 1029, 'OBJ_EVENT_GFX_JOHTO_SILVER': 1030, 'OBJ_EVENT_GFX_JOHTO_KESTRA': 1031,
           'OBJ_EVENT_GFX_REGIONAL_HOENN': 1032, 'OBJ_EVENT_GFX_REGIONAL_KANTO': 1033, 'OBJ_EVENT_GFX_REGIONAL_JOHTO': 1034,
           'OBJ_EVENT_GFX_REGIONAL_SINNOH': 1035, 'OBJ_EVENT_GFX_REGIONAL_UNOVA': 1036,
           'OBJ_EVENT_GFX_JOHTO_BOY': 1024, 'OBJ_EVENT_GFX_JOHTO_GIRL': 1025, 'OBJ_EVENT_GFX_JOHTO_MAN': 1026, 'OBJ_EVENT_GFX_JOHTO_WOMAN': 1027}
    inter = []
    for npc in cast.NPCS:
        x, y = npc['pos']; key = 64  # face up towards the NPC one cell above
        inter.append(f'  interaction({gid[npc["gfx"]]},{x},{y + 1},64,"{npc["id"].lower()}-dialogue");')
    src = TEMPLATE
    src = src.replace('RUNTIME_C', str(ROOT / 'tools/gba/maps/runtime.c'))
    src = src.replace('SPAWN_X', str(L.SPAWN[0])).replace('SPAWN_Y', str(L.SPAWN[1]))
    src = src.replace('NDOORS', str(len(order))).replace('DOORS', ','.join(f'{{{x},{y}}}' for x, y in door_cells))
    src = src.replace('DOOR_MAPS', ','.join(str(MAP_INDEX[n]) for n in order))
    src = src.replace('EXITS', ','.join(f'{{{EXITS[n][0]},{EXITS[n][1]}}}' for n in order))
    src = src.replace('EAST_X', str(L.W - 1)).replace('EAST_Y', str(L.EAST_EXIT[0] + 1))
    src = src.replace('NORTH_X', str(L.NORTH_EXIT[0] + 1)).replace('NORTH_Y', '1')
    shore_y = 14; src = src.replace('SHORE_MIN', str(L.shore(shore_y))).replace('SHORE_X', str(L.shore(shore_y) + 2)).replace('SHORE_Y', str(shore_y))
    src = src.replace('NVIEWS', str(len(views))).replace('VIEWS', ','.join(f'{{{x},{y}}}' for x, y in views))
    src = src.replace('INTERACTIONS', '\n'.join(inter))
    src = src.replace('SHOTS', '\n'.join(f'  go(0,{x},{y});screenshot(argv[3],"{tag}");' for tag, x, y in shots))
    return src, views, shots

def main():
    game = Path(sys.argv[1]).resolve(); out = Path(sys.argv[2]).resolve(); out.mkdir(parents=True, exist_ok=False)
    src, views, shots = generate(); csrc = out / 'town_runtime.c'; csrc.write_text(src)
    (HERE / 'generated').mkdir(exist_ok=True); (HERE / 'generated' / 'town_runtime.c').write_text(src)
    flags = shlex.split(os.environ.get('MGBA_FLAGS', ''))
    if not flags and Path('/opt/homebrew/opt/mgba').exists(): flags = ['-I/opt/homebrew/opt/mgba/include', '-L/opt/homebrew/opt/mgba/lib', '-lmgba']
    if not flags: flags = ['-lmgba']
    subprocess.run(['cc', str(csrc), *flags, '-o', str(out / 'runtime')], check=True)
    lines = subprocess.check_output([str(TOOLCHAIN / 'bin/arm-none-eabi-nm'), str(game / 'pokeemerald.elf')], text=True)
    wanted = {'MapProof_Boot', 'MapProof_Enter', 'MapProof_ReadState', 'MapProof_Resume', 'gMapProofState', 'TrySavingData', 'LoadGameSave', 'ArePlayerFieldControlsLocked', 'gObjectEvents', 'gSprites'}
    symbols = {r[2]: r[0] for l in lines.splitlines() if len(r := l.split()) == 3 and r[2] in wanted}; assert symbols.keys() == wanted, wanted - symbols.keys()
    (out / 'symbols.txt').write_text(''.join(f'{k} {v}\n' for k, v in symbols.items()))
    results = []
    phases = sys.argv[3:] or ['write', 'read', 'menu', 'walk']
    for phase in phases:
        r = subprocess.run([str(out / 'runtime'), str(game / 'pokeemerald.gba'), str(out / 'symbols.txt'), str(out), phase], capture_output=True, text=True, timeout=900)
        (out / (phase + '.jsonl')).write_text(r.stdout)
        results.append(dict(phase=phase, exit_code=r.returncode, stderr=r.stderr, observations=[json.loads(l) for l in r.stdout.splitlines() if l.startswith('{') and 'objects' not in l]))
        (out / 'results.json').write_text(json.dumps(results, indent=2) + '\n')
        for file in out.glob('*.ppm'):
            Image.open(file).save(file.with_suffix('.png')); file.unlink()
        print(phase, r.returncode, r.stderr[-400:], flush=True)
        if r.returncode != 0: sys.exit(r.returncode)
    print('All phases passed.')

if __name__ == '__main__':
    main()
