#!/usr/bin/env python3
"""import_sinnoh.py - port the Platinum Sinnoh overworld into the HGSS build.

What it does (idempotent — safe to re-run):
  1. Reads Platinum overworld matrix 0 (30x30) + its land chunks, headers, areas.
  2. Converts each land chunk to HGSS container format:
       Plat:  u32 sizes[4] | perms | props | BMD0 | BDHC
       HGSS:  u32 sizes[4] | u16 0x1234, u16 extraLen | perms | props | BMD0 | BDHC
     Building props are kept: their 48-byte entries pass through with the
     model id (u32 at offset 0) remapped to the appended HGSS global id.
  3. Imports the Platinum building models the used areas need:
     appends them to bm_field.narc (mirrored at files/a/0/4/0 — the engine
     reads models from a/0/4/0, byte-identical duplicate), extends
     bm_field_matshp.dat with each model's Platinum locator+id records
     (read for EVERY rendered prop, so appended ids must be covered), and
     appends per-area build lists (a/0/4/3) + Platinum prop texture sets
     (a/0/7/0) at parallel indices. HGSS's model-file array holds 550
     slots (asm free-loop bound 0x226); 340 vanilla + ~140 imported fits.
  4. Appends chunks to files/a/0/6/5, Platinum tilesets (NSBTX) to a/0/4/4,
     new area-data entries to a/0/4/2.
  5. Writes a new matrix bin map_matrix_0288_SINNOH.bin (headers/altitudes/models).
  6. Patches include/constants/maps.h and src/data/map_headers.h between
     APOC_REGIONPORT markers with the new MAP_APOC_SINNOH_* headers.
  7. Emits build/sinnoh_manifest.json for the ferry-wiring step.

Idempotency: NARCs are truncated to the known vanilla member counts before
appending (git HEAD now contains imported NARCs, so reading blobs is not
enough); see load_vanilla().
"""
import json
import os
import re
import struct
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from narc import narc_read, narc_write  # noqa: E402

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
HG = os.path.join(ROOT, "disasm", "pokeheartgold")
PLAT = os.path.join(ROOT, "disasm", "pokeplatinum")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "build")

MATRIX_NAME = "map_matrix_0288_SINNOH.bin"
FIRST_NEW_MAP_ID = 540
MARK_BEGIN = "// APOC_REGIONPORT SINNOH BEGIN (generated by tools/regionport/import_sinnoh.py)"
MARK_END = "// APOC_REGIONPORT SINNOH END"


# Vanilla member counts. HEAD contains already-imported NARCs, so pristine
# state is recovered by truncating: this importer only ever appends members.
VANILLA_COUNTS = {
    "files/a/0/6/5": 676,
    "files/a/0/4/2": 106,
    "files/a/0/4/3": 104,
    "files/a/0/4/4": 106,
    "files/a/0/7/0": 104,
    "files/a/0/4/0": 340,
    "files/a/1/0/7": 340,
}
# a/1/0/7 "no animations for this model" member (24B, used by 194 vanilla models).
# HGSS reads member[modelID] of this NARC UNGUARDED for every model in a build
# list (unlike Platinum), so every appended model id needs a member here.
NO_ANIM_MEMBER = bytes.fromhex("ffff000000000000" + "ff" * 16)
VANILLA_MATSHP = (340, 733)  # locators, ids


def load_vanilla(relpath):
    """Pristine members of an HGSS NARC (current file truncated to the vanilla count)."""
    members = narc_read(os.path.join(HG, relpath))
    n = VANILLA_COUNTS[relpath]
    assert len(members) >= n, (relpath, len(members), n)
    return members[:n]


def convert_land(plat_bin, hgss_types=None, model_map=None):
    perms_sz, props_sz, model_sz, bdhc_sz = struct.unpack_from("<4I", plat_bin, 0)
    assert perms_sz == 0x800, perms_sz
    o = 16
    perms = bytearray(plat_bin[o:o + perms_sz]); o += perms_sz
    if hgss_types:
        for i in range(0, perms_sz, 2):
            if not (perms[i + 1] & 0x80) and perms[i] not in hgss_types:
                perms[i] = 0x00
    perms = bytes(perms)
    props = bytearray(plat_bin[o:o + props_sz]); o += props_sz
    assert props_sz % 48 == 0, props_sz
    for i in range(0, props_sz, 48):
        pid = struct.unpack_from("<I", props, i)[0]
        struct.pack_into("<I", props, i, (model_map or {}).get(pid, 0))
    props = bytes(props)
    model = plat_bin[o:o + model_sz]; o += model_sz
    bdhc = plat_bin[o:o + bdhc_sz]
    assert model[:4] == b"BMD0" and bdhc[:4] == b"BDHC"
    return (struct.pack("<4I", perms_sz, len(props), model_sz, bdhc_sz)
            + struct.pack("<HH", 0x1234, 0) + perms + props + model + bdhc)


def parse_plat_headers():
    """MAP_HEADER_* -> {areaDataArchiveID, mapType} from Platinum's C table."""
    with open(os.path.join(PLAT, "include", "data", "map_headers.h")) as f:
        src = f.read()
    out = {}
    for m in re.finditer(r"\[(MAP_HEADER_\w+)\]\s*=\s*\{(.*?)\}", src, re.S):
        name, body = m.group(1), m.group(2)
        fields = dict(re.findall(r"\.(\w+)\s*=\s*([^,\n]+)", body))
        out[name] = {
            "area": int(fields["areaDataArchiveID"], 0),
            "mapType": int(fields.get("mapType", "0x2"), 0),
        }
    return out


def main():
    os.makedirs(OUT, exist_ok=True)

    # ---- Platinum inputs -------------------------------------------------- #
    with open(os.path.join(PLAT, "res/field/maps/matrices/map_matrix_000.json")) as f:
        mat = json.load(f)
    headers_grid = mat["headers"]          # 30x30 of MAP_HEADER_*
    alt_grid = mat["altitudes"]
    maps_grid = mat["maps"]                # 30x30 of MAP_nnn
    H, W = len(maps_grid), len(maps_grid[0])
    plat_headers = parse_plat_headers()

    plat_area = narc_read(os.path.join(PLAT, "res/prebuilt/fielddata/areadata/area_data.narc"))

    # Void bridging: vanilla crosses some spans via interior maps (their own
    # matrices), leaving MAP_NONE bands in the overworld grid. Fill the cells a
    # causeway must cross with a copy of an adjacent filler chunk.
    VOID_FILL = [(11, 14, 11, 15)]  # (col,row) <- model/altitude of (srccol,srcrow)
    for c, r, sc, sr in VOID_FILL:
        maps_grid[r][c] = maps_grid[sr][sc]
        alt_grid[r][c] = alt_grid[sr][sc]

    land_ids = sorted({int(m[4:]) for row in maps_grid for m in row if m != "MAP_NONE"})
    header_names = []
    for row in headers_grid:
        for h in row:
            if h != "MAP_HEADER_EVERYWHERE" and h not in header_names:
                header_names.append(h)
    print(f"platinum matrix: {W}x{H}, {len(land_ids)} chunks, {len(header_names)} headers")

    # ---- HGSS vanilla NARCs ----------------------------------------------- #
    land = load_vanilla("files/a/0/6/5")
    area_data = load_vanilla("files/a/0/4/2")
    area_build = load_vanilla("files/a/0/4/3")
    tex_sets = load_vanilla("files/a/0/4/4")
    prop_tex = load_vanilla("files/a/0/7/0")
    bm_field = load_vanilla("files/a/0/4/0")
    n_land0, n_area0, n_tex0 = len(land), len(area_data), len(tex_sets)
    print(f"HGSS vanilla: {n_land0} land, {n_area0} areas, {n_tex0} texsets, "
          f"{len(bm_field)} building models")

    # ---- building models ---------------------------------------------------- #
    # Union of Platinum model ids across the used areas' build lists, appended
    # to HGSS's building NARC. Global ids: vanilla 0..339, imported 340+.
    plat_areas_used = sorted({plat_headers[h]["area"] for h in header_names})
    plat_ab = narc_read(os.path.join(
        PLAT, "res/prebuilt/fielddata/areadata/area_build_model/area_build.narc"))
    plat_bm_tex = narc_read(os.path.join(
        PLAT, "res/prebuilt/fielddata/areadata/area_build_model/areabm_texset.narc"))
    plat_bm = narc_read(os.path.join(
        PLAT, "res/prebuilt/fielddata/build_model/build_model.narc"))
    plat_build_of = {}
    needed = set()
    for pa in plat_areas_used:
        bl = struct.unpack_from("<H", plat_area[pa], 0)[0]
        cnt = struct.unpack_from("<H", plat_ab[bl], 0)[0]
        ids = struct.unpack_from(f"<{cnt}H", plat_ab[bl], 2)
        plat_build_of[pa] = (bl, ids)
        needed.update(ids)
    plat_models = sorted(needed)
    model_map = {pid: len(bm_field) + i for i, pid in enumerate(plat_models)}
    assert len(bm_field) + len(plat_models) <= 550, "HGSS model-file array overflow"
    bm_field.extend(plat_bm[pid] for pid in plat_models)
    anim_list = load_vanilla("files/a/1/0/7")
    anim_list.extend([NO_ANIM_MEMBER] * len(plat_models))
    print(f"building models: +{len(plat_models)} (ids "
          f"{model_map[plat_models[0]]}..{model_map[plat_models[-1]]})")

    # matshp.dat: per-model (idsCount, idsIndex) locators + id pairs, read for
    # every rendered prop — extend it in appended-id order from Platinum's.
    with open(os.path.join(PLAT, "res/prebuilt/fielddata/build_model/build_model_matshp.dat"), "rb") as f:
        pm = f.read()
    plc, pic = struct.unpack_from("<HH", pm, 0)
    ploc = [struct.unpack_from("<HH", pm, 4 + i * 4) for i in range(plc)]
    pids = pm[4 + plc * 4:4 + plc * 4 + pic * 4]
    with open(os.path.join(HG, "files/fielddata/build_model/bm_field_matshp.dat"), "rb") as f:
        hm = f.read()
    nloc, nids = VANILLA_MATSHP
    # Recover the pristine vanilla records. The current file may already contain
    # imported members from a prior run, so the ids table starts after the
    # file's ACTUAL locator count -- NOT after `nloc`. Using a fixed byte offset
    # here corrupts the vanilla ids on every re-run (they get overwritten with
    # the appended locator bytes). Locate the ids table from the live header.
    cur_nloc = struct.unpack_from("<H", hm, 0)[0]
    ids_base = 4 + cur_nloc * 4
    hloc = bytearray(hm[4:4 + nloc * 4])
    hids = bytearray(hm[ids_base:ids_base + nids * 4])
    for pid in plat_models:
        cnt, idx = ploc[pid]
        hloc += struct.pack("<HH", cnt, len(hids) // 4)
        hids += pids[idx * 4:(idx + cnt) * 4]
    matshp = struct.pack("<HH", len(hloc) // 4, len(hids) // 4) + bytes(hloc) + bytes(hids)

    # ---- land chunks ------------------------------------------------------ #
    # Terrain type bytes HGSS's movement engine knows: collect every type used
    # on a walkable tile anywhere in vanilla. Platinum-only codes (e.g. 0x15,
    # the R218 drawbridge) hard-block movement in HGSS, so unknown walkable
    # types get normalized to plain ground.
    hgss_types = set()
    for mem in land:
        _, n = struct.unpack_from("<HH", mem, 16)
        pl = mem[20 + n:20 + n + 0x800]
        for i in range(0, 0x800, 2):
            if not (pl[i + 1] & 0x80):
                hgss_types.add(pl[i])

    land_map = {}  # plat land id -> new HGSS member id
    for lid in land_ids:
        with open(os.path.join(PLAT, f"res/field/maps/data/map_data_{lid:03}.bin"), "rb") as f:
            land_map[lid] = len(land)
            land.append(convert_land(f.read(), hgss_types, model_map))

    # Vanilla Sinnoh chains its outdoor areas through interior maps we don't
    # port (gatehouses, Oreburgh Gate, Ravaged Path, Mt. Coronet passages...),
    # so the raw overworld is partitioned. Carve short walkable causeways at
    # the narrowest seams between large walkable components so the whole
    # region is traversable on foot. Prefers carving through building/gate
    # footprints (type 0) over water.
    carve_causeways(land, land_map, maps_grid, W, H)

    # ---- areas + tilesets -------------------------------------------------- #
    # one shared empty build list + dummy prop texture, same index in both NARCs
    # (kept at index 104 — import_hoenn.py's SHARED_EMPTY_BUILD points here)
    shared_build_id = len(area_build)
    assert len(area_build) == len(prop_tex), (len(area_build), len(prop_tex))
    area_build.append(struct.pack("<HH", 0, 0))
    prop_tex.append(min(prop_tex, key=len))  # smallest vanilla BTX0, never uploaded

    # per-area: translated build list (a/0/4/3) + Platinum prop texture set
    # (a/0/7/0) at the same index — one u16 in the area record selects both
    tex_map, area_map = {}, {}
    for pa in plat_areas_used:
        _, ptex, _, _ = struct.unpack("<4H", plat_area[pa])
        if ptex not in tex_map:
            with open(os.path.join(PLAT, f"res/field/maps/texture_sets/map_texture_set_{ptex:03}.nsbtx"), "rb") as f:
                tex_map[ptex] = len(tex_sets)
                tex_sets.append(f.read())
        bl, ids = plat_build_of[pa]
        build_id = len(area_build)
        area_build.append(struct.pack(f"<H{len(ids)}H", len(ids),
                                      *[model_map[i] for i in ids]))
        prop_tex.append(plat_bm_tex[bl])
        area_map[pa] = len(area_data)
        area_data.append(struct.pack("<4H", build_id, tex_map[ptex], 0xFFFF, 0x0101))
    print(f"imported {len(tex_map)} tilesets, {len(area_map)} areas, {len(land_ids)} chunks")

    # ---- new map ids ------------------------------------------------------- #
    id_map = {}
    for i, h in enumerate(header_names):
        id_map[h] = (FIRST_NEW_MAP_ID + i, "MAP_APOC_SINNOH_" + h[len("MAP_HEADER_"):])

    # ---- matrix bin --------------------------------------------------------- #
    sys.path.insert(0, os.path.join(ROOT, "tools", "mapeditor"))
    from mapdata import MapMatrix
    mm = MapMatrix(
        width=W, height=H, name="SINNOH",
        models=[0xFFFF if m == "MAP_NONE" else land_map[int(m[4:])]
                for row in maps_grid for m in row],
        headers=fill_headers(headers_grid, maps_grid, id_map, W, H),
        altitudes=[a for row in alt_grid for a in row],
    )
    with open(os.path.join(HG, "files/fielddata/mapmatrix/map_matrix", MATRIX_NAME), "wb") as f:
        f.write(mm.serialize())

    # ---- C patches ---------------------------------------------------------- #
    defines = [MARK_BEGIN]
    for h in header_names:
        mid, cname = id_map[h]
        defines.append(f"#define {cname:<49} {mid}")
    defines.append(MARK_END)
    patch_between_markers(
        os.path.join(HG, "include/constants/maps.h"),
        "\n".join(defines), anchor="#endif // POKEHEARTGOLD_CONSTANTS_MAPS_H")

    # per-map overrides: sinnoh_life.py (events/scripts/msg/encounter banks)
    # persists its choices to build/sinnoh_overrides.json; fall back to the
    # original ferry-arrival wiring if it hasn't been run.
    ov_path = os.path.join(OUT, "sinnoh_overrides.json")
    if os.path.exists(ov_path):
        with open(ov_path) as f:
            overrides = json.load(f)
    else:
        overrides = {
            "MAP_HEADER_CANALAVE_CITY": {
                "scriptsBank": "NARC_scr_seq_scr_seq_0850_T21_bin",
                "eventsBank": "NARC_zone_event_491_APOCSINNOH_bin",
            },
        }
    entries = [MARK_BEGIN]
    for h in header_names:
        mid, cname = id_map[h]
        ov = overrides.get(h, {})
        scripts_bank = ov.get("scriptsBank", "NARC_scr_seq_scr_seq_0139_EVERYWHERE_bin")
        events_bank = ov.get("eventsBank", "NARC_zone_event_000_DUMMY_bin")
        msg_bank = ov.get("msgBank", "NARC_msg_msg_0003_EVERYWHERE_bin")
        enc_bank = ov.get("wildEncounterBank", "ENCDATA_NA")
        ptype = plat_headers[h]["mapType"]
        map_type = "MAP_TYPE_CITY_TOWN" if ptype == 1 else "MAP_TYPE_ROUTE"
        entries.append(f"""    [{cname}] = {{
                        .wildEncounterBank = {enc_bank},
                        .areaDataBank = {area_map[plat_headers[h]["area"]]},
                        .moveModelBank = 15,
                        .worldMapX = 0,
                        .worldMapY = 0,
                        .matrixId = NARC_map_matrix_{MATRIX_NAME.replace('.', '_')},
                        .scriptsBank = {scripts_bank},
                        .scriptHeaderBank = NARC_scr_seq_scr_seq_0399_EVERYWHERE_hdr_bin,
                        .msgBank = {msg_bank},
                        .dayMusicId = SEQ_GS_R_1_30,
                        .nightMusicId = SEQ_GS_R_1_30,
                        .eventsBank = {events_bank},
                        .mapsec = MAPSEC_MYSTERY_ZONE,
                        .areaIcon = 3,
                        .momCallIntroParam = 10,
                        .isKanto = FALSE,
                        .weather = 0,
                        .mapType = {map_type},
                        .cameraType = 0,
                        .followMode = MAP_FOLLOWMODE_ALLOW,
                        .battleBg = BATTLE_BG_GENERAL,
                        .bikeAllowed = TRUE,
                        .runningAllowed_Unused = TRUE,
                        .escapeRopeAllowed = FALSE,
                        .flyAllowed = FALSE,
                        .outgoingCalls = FALSE,
                        .incomingCalls = FALSE,
                        .radioSignal = FALSE,
    }},""")
    entries.append(MARK_END)
    patch_map_headers(os.path.join(HG, "src/data/map_headers.h"), "\n".join(entries))

    # ---- write NARCs -------------------------------------------------------- #
    narc_write(os.path.join(HG, "files/a/0/6/5"), land)
    narc_write(os.path.join(HG, "files/a/0/4/2"), area_data)
    narc_write(os.path.join(HG, "files/a/0/4/3"), area_build)
    narc_write(os.path.join(HG, "files/a/0/4/4"), tex_sets)
    narc_write(os.path.join(HG, "files/a/0/7/0"), prop_tex)
    # engine reads models from a/0/4/0; bm_field.narc is its byte-identical twin
    narc_write(os.path.join(HG, "files/a/0/4/0"), bm_field)
    narc_write(os.path.join(HG, "files/fielddata/build_model/bm_field.narc"), bm_field)
    narc_write(os.path.join(HG, "files/a/1/0/7"), anim_list)
    with open(os.path.join(HG, "files/fielddata/build_model/bm_field_matshp.dat"), "wb") as f:
        f.write(matshp)

    # ---- manifest ------------------------------------------------------------ #
    manifest = {
        "matrix": MATRIX_NAME,
        "matrix_size": [W, H],
        "first_map_id": FIRST_NEW_MAP_ID,
        "maps": {h: {"id": id_map[h][0], "name": id_map[h][1]} for h in header_names},
        "headers_grid": [[id_map[h][1] if h in id_map else None for h in row]
                         for row in headers_grid],
        "land_grid": [[None if m == "MAP_NONE" else land_map[int(m[4:])] for m in row]
                      for row in maps_grid],
        "land_base": n_land0,
    }
    with open(os.path.join(OUT, "sinnoh_manifest.json"), "w") as f:
        json.dump(manifest, f, indent=1)
    print(f"done: land {n_land0}->{len(land)}, areas {n_area0}->{len(area_data)}, "
          f"texsets {n_tex0}->{len(tex_sets)}; map ids {FIRST_NEW_MAP_ID}.."
          f"{FIRST_NEW_MAP_ID + len(header_names) - 1}")


def fill_headers(headers_grid, maps_grid, id_map, W, H):
    """Per-cell header ids; chunk-bearing cells with no real header get the
    nearest real one (a header-0 cell would swap the player onto the Johto
    matrix, since the header's matrixId is what keeps the world loaded)."""
    from collections import deque
    ids = [[id_map[h][0] if h in id_map else None for h in row] for row in headers_grid]
    q = deque((x, y) for y in range(H) for x in range(W) if ids[y][x] is not None)
    while q:
        x, y = q.popleft()
        for dx, dy in ((0, 1), (0, -1), (1, 0), (-1, 0)):
            nx, ny = x + dx, y + dy
            if 0 <= nx < W and 0 <= ny < H and ids[ny][nx] is None:
                ids[ny][nx] = ids[y][x]
                q.append((nx, ny))
    return [ids[y][x] if ids[y][x] is not None else 0
            for y in range(H) for x in range(W)]


WATER_TYPES = {0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x19, 0x2A, 0x50, 0x51, 0x52, 0x53, 0x73, 0x78, 0x7C}  # bit0 of the engine's _020FCA74 behavior table


def carve_causeways(land, land_map, maps_grid, W, H, seed=(38, 743),
                    min_comp=250, max_gap=48, long_gap=96, long_min=2000):
    """Grow the on-foot-reachable set from the ferry arrival tile: repeatedly
    find the cheapest straight seam (blocked/water gap, small pockets passed
    through) from the reachable set to a sizable unreached component, carve it
    to plain ground, repeat. Vanilla chains these areas through interior maps
    (gates, caves, dynamic bridges) that we don't port."""
    from collections import deque

    GW, GH = W * 32, H * 32
    bufs = {}
    for cz in range(H):
        for cx in range(W):
            mname = maps_grid[cz][cx]
            if mname == "MAP_NONE":
                continue
            mid = land_map[int(mname[4:])]
            if mid not in bufs:
                b = bytearray(land[mid])
                _, n = struct.unpack_from("<HH", b, 16)
                bufs[mid] = (b, 20 + n)

    def cell_mid(x, z):
        if not (0 <= x < GW and 0 <= z < GH):
            return None
        mname = maps_grid[z // 32][x // 32]
        return None if mname == "MAP_NONE" else land_map[int(mname[4:])]

    def tile(x, z):
        mid = cell_mid(x, z)
        if mid is None:
            return None, None
        b, base = bufs[mid]
        i = base + ((z % 32) * 32 + (x % 32)) * 2
        return b[i], b[i + 1]

    def carve(x, z):
        mid = cell_mid(x, z)
        b, base = bufs[mid]
        i = base + ((z % 32) * 32 + (x % 32)) * 2
        b[i] = 0x00
        b[i + 1] = 0x00

    def walkable(x, z):
        t, c = tile(x, z)
        return t is not None and not (c & 0x80) and t not in WATER_TYPES

    def flood(seeds):
        seen = set(s_ for s_ in seeds if walkable(*s_))
        q = deque(seen)
        while q:
            x, z = q.popleft()
            for dx, dz in ((0, 1), (0, -1), (1, 0), (-1, 0)):
                n = (x + dx, z + dz)
                if n not in seen and walkable(*n):
                    seen.add(n)
                    q.append(n)
        return seen

    assert walkable(*seed), "ferry arrival tile not walkable"
    carve_count = 0
    while True:
        reach = flood([seed])
        # component sizes of unreached walkable tiles
        comp_of, comps = {}, []
        for z0 in range(GH):
            for x0 in range(GW):
                if (x0, z0) in reach or (x0, z0) in comp_of or not walkable(x0, z0):
                    continue
                cid = len(comps)
                tiles_, q = [], deque([(x0, z0)])
                comp_of[(x0, z0)] = cid
                while q:
                    x, z = q.popleft()
                    tiles_.append((x, z))
                    for dx, dz in ((0, 1), (0, -1), (1, 0), (-1, 0)):
                        n = (x + dx, z + dz)
                        if n not in comp_of and n not in reach and walkable(*n):
                            comp_of[n] = cid
                            q.append(n)
                comps.append(tiles_)
        big_left = sum(1 for t in comps if len(t) >= min_comp)
        if not big_left:
            print(f"causeways: done, {carve_count} carved; "
                  f"{len(reach)} tiles reachable on foot")
            break
        best = None  # (score, x, z, dx, dz, gap)
        for (x, z) in reach:
            for dx, dz in ((0, 1), (0, -1), (1, 0), (-1, 0)):
                nx, nz, gap, water = x + dx, z + dz, 0, 0
                while gap <= long_gap:
                    t, c = tile(nx, nz)
                    if t is None:
                        break
                    if (c & 0x80) or t in WATER_TYPES:
                        gap += 1
                        water += 1 if t in WATER_TYPES else 0
                        nx += dx
                        nz += dz
                        continue
                    if (nx, nz) in reach:
                        break
                    csize = len(comps[comp_of[(nx, nz)]])
                    if gap and csize >= min_comp:
                        limit = long_gap if csize >= long_min else max_gap
                        if gap <= limit:
                            score = gap + 6 * water
                            if best is None or score < best[0]:
                                best = (score, x, z, dx, dz, gap)
                    elif csize < min_comp:
                        # tiny pocket: pass through it toward something big
                        gap += 1
                        nx += dx
                        nz += dz
                        continue
                    break
        if best is None:
            print(f"causeways: no more seams ({big_left} big areas left unreached); "
                  f"{len(reach)} tiles reachable on foot")
            break
        _, x, z, dx, dz, gap = best
        for k in range(1, gap + 1):
            carve(x + dx * k, z + dz * k)
        carve_count += 1
        print(f"causeways: carved {gap} tiles at ({x},{z}) d=({dx},{dz})")

    for mid, (b, _) in bufs.items():
        land[mid] = bytes(b)


def patch_between_markers(path, block, anchor):
    with open(path) as f:
        src = f.read()
    src = remove_block(src)
    assert anchor in src, f"anchor missing in {path}"
    src = src.replace(anchor, block + "\n\n" + anchor)
    with open(path, "w") as f:
        f.write(src)


def patch_map_headers(path, block):
    with open(path) as f:
        src = f.read()
    src = remove_block(src)
    # insert before the closing of sMapHeaders (last "};" in file)
    idx = src.rstrip().rfind("};")
    assert idx > 0
    src = src[:idx] + block + "\n" + src[idx:]
    with open(path, "w") as f:
        f.write(src)


def remove_block(src):
    i = src.find(MARK_BEGIN)
    if i < 0:
        return src
    j = src.find(MARK_END)
    assert j > i
    j += len(MARK_END)
    while j < len(src) and src[j] == "\n":
        j += 1
    return src[:i] + src[j:]


if __name__ == "__main__":
    main()
