#!/usr/bin/env python3
"""import_hoenn.py - rebuild the Emerald Hoenn overworld inside the HGSS build.

Emerald is GBA, so nothing lifts directly: this generates HGSS assets from the
pokeemerald layout data (run AFTER import_sinnoh.py — it appends to the NARCs
at the counts import_sinnoh leaves behind, and truncates back to them on
re-runs so it is idempotent).

Per 32x32 chunk of the stitched 49-map overworld (emeraldmap.stitch):
  perms  : collision+behavior mapped to HGSS types (grass 0x02, water 0x15,
           ledges/doors/blocked 0x80)
  model  : generated NSBMD (nsbmd.py 39-slot chunk template) — v6 Gen-4
           re-skin: every tile is classified semantically (hoenn_texmap.py)
           and drawn as merged repeat-UV rects of vanilla HGSS/Platinum
           donor terrain textures, with cutout overlays (encounter grass,
           flowers, water surface) and real hedge-wall tree quads
           (hoenn_ground.py). The GBA art only steers classification now —
           no Emerald pixel ever reaches the ROM.
  bdhc   : flat template plane (elevation geometry is a later round)

ONE shared area for the whole region: the engine only renders chunks whose
owner map's area matches the currently-loaded one (crossing a map header
boundary swaps areas and blanks all foreign chunks — the v1 black-chunk bug),
so every Hoenn header points at a single area entry / NSBTX. All chunks bind
the SAME donor texture list in the same material slots.
One matrix (map_matrix_0289_HOENN.bin) + 45 headers.
"""
import json
import os
import struct
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from narc import narc_read, narc_write            # noqa: E402
import emeraldmap as em                           # noqa: E402
import nsbmd                                      # noqa: E402
import hoenn_buildings as hb                      # noqa: E402
import hoenn_ground as hg2                        # noqa: E402
from PIL import Image                             # noqa: E402

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
HG = os.path.join(ROOT, "disasm", "pokeheartgold")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "build")

sys.path.insert(0, os.path.join(ROOT, "tools", "mapeditor"))
from mapdata import MapMatrix                     # noqa: E402

MATRIX_NAME = "map_matrix_0289_HOENN.bin"
FIRST_NEW_MAP_ID = 606
MARK_BEGIN = "// APOC_REGIONPORT HOENN BEGIN (generated by tools/regionport/import_hoenn.py)"
MARK_END = "// APOC_REGIONPORT HOENN END"

# NARC member counts as import_sinnoh.py leaves them (truncate-to on re-run)
BASE = {"land": 852, "area": 119, "tex": 119, "build": 118, "prop": 118}
SHARED_EMPTY_BUILD = 104  # empty build list + dummy prop texture from Sinnoh run

WATER_HG = 0x15
GRASS_HG = 0x02

EM_WATER = set(range(0x10, 0x1B)) | {0x50, 0x51, 0x52, 0x53}
EM_GRASS = {0x02, 0x03, 0x09, 0x24}
EM_BLOCKED_BEH = set(range(0x30, 0x40)) | set(range(0x60, 0x74)) | {0x01}

# flat BDHC template: smallest vanilla Platinum one
with open(os.path.join(ROOT, "disasm/pokeplatinum/res/field/maps/data/map_data_619.bin"), "rb") as f:
    _b = f.read()
    _p, _pr, _mo, _bd = struct.unpack_from("<4I", _b, 0)
    FLAT_BDHC = _b[16 + _p + _pr + _mo:16 + _p + _pr + _mo + _bd]
assert FLAT_BDHC[:4] == b"BDHC"


def stitch_world():
    """Global tile grid: per tile (owner map id, content key, perm bytes)."""
    _, _, origins = em.stitch(["MAP_LITTLEROOT_TOWN", "ALL"])
    GW = max(o[0] + o[2] for o in origins.values())
    GH = max(o[1] + o[3] for o in origins.values())
    owner = [[None] * GW for _ in range(GH)]
    ckey = [[None] * GW for _ in range(GH)]
    perm = [[(0x00, 0x80)] * GW for _ in range(GH)]
    for mid, (gx, gy, w, h) in origins.items():
        m = em.MapData(mid)
        for ty in range(h):
            for tx in range(w):
                v = m.blocks[ty * w + tx]
                mt, coll = v & 0x3FF, (v >> 10) & 3
                _, beh = m.metatile_def(mt)
                if beh in EM_WATER:
                    p = (WATER_HG, 0x00)
                elif coll or beh in EM_BLOCKED_BEH:
                    p = (0x00, 0x80)
                elif beh in EM_GRASS:
                    p = (GRASS_HG, 0x00)
                else:
                    p = (0x00, 0x00)
                owner[gy + ty][gx + tx] = mid
                ckey[gy + ty][gx + tx] = (mid, mt)
                perm[gy + ty][gx + tx] = p
    return GW, GH, owner, ckey, perm, origins


_tile_img_cache = {}


def tile_image(mapdatas, mid, mt):
    """Render one metatile to 16x16 RGB bytes; content-cached."""
    k = (mid, mt)
    if k in _tile_img_cache:
        return _tile_img_cache[k]
    m = mapdatas[mid]
    mdef, _ = m.metatile_def(mt)
    img = Image.new("RGB", (16, 16), (0, 0, 0))
    px = img.load()
    pals = m.palettes()
    if mdef is not None:
        for layer in range(2):
            for sub in range(4):
                v = mdef[layer * 4 + sub]
                tid, hf, vf, pal = v & 0x3FF, v & 0x400, v & 0x800, (v >> 12) & 0xF
                rows = m.subtile_pixels(tid)
                colors = pals[pal] if pal < len(pals) else [(0, 0, 0)] * 16
                ox, oy = (sub % 2) * 8, (sub // 2) * 8
                for ry in range(8):
                    srow = rows[7 - ry] if vf else rows[ry]
                    for rx in range(8):
                        ci = srow[7 - rx] if hf else srow[rx]
                        if layer == 1 and ci == 0:
                            continue
                        c = colors[ci] if ci < len(colors) else (0, 0, 0)
                        px[ox + rx, oy + ry] = hb.lift(c)
    data = img.tobytes()
    _tile_img_cache[k] = data
    return data


def greedy_rects(cells):
    cells = set(cells)
    rects = []
    while cells:
        x, z = min(cells, key=lambda t: (t[1], t[0]))
        w = 1
        while (x + w, z) in cells:
            w += 1
        h = 1
        while all((x + i, z + h) in cells for i in range(w)):
            h += 1
        for i in range(w):
            for j in range(h):
                cells.discard((x + i, z + j))
        rects.append((x, z, w, h))
    return rects


def tile_quad(lx, lz, w, h, s0, t0, s1, t1, y=0.0):
    """Chunk-local tile rect -> world quad with texcoords (texels)."""
    x0, z0 = lx * 16 - 256, lz * 16 - 256
    x1, z1 = x0 + w * 16, z0 + h * 16
    return [((x0, y, z0), (s0, t0)), ((x1, y, z0), (s1, t0)),
            ((x1, y, z1), (s1, t1)), ((x0, y, z1), (s0, t1))]


def main():
    os.makedirs(OUT, exist_ok=True)
    print("stitching hoenn...")
    GW, GH, owner, ckey, perm, origins = stitch_world()
    CW, CH = (GW + 31) // 32, (GH + 31) // 32
    print(f"grid {GW}x{GH} tiles -> {CW}x{CH} chunks")
    # 3D buildings: extract footprints + art, flatten footprints in ckey so
    # the ground renders as plain terrain under the generated prop models
    binfo = hb.prepare(origins, ckey)
    mapdatas = {mid: em.MapData(mid) for mid in origins}

    # ---- chunk ownership --------------------------------------------------- #
    chunk_owner = {}
    for cy in range(CH):
        for cx in range(CW):
            oc = Counter()
            for z in range(cy * 32, min(cy * 32 + 32, GH)):
                for x in range(cx * 32, min(cx * 32 + 32, GW)):
                    if owner[z][x]:
                        oc[owner[z][x]] += 1
            if not oc:
                continue
            chunk_owner[(cx, cy)] = oc.most_common(1)[0][0]

    # ---- Gen-4 semantic re-skin (v6) --------------------------------------- #
    # Classify every tile semantically (behavior/curated/heuristic) and draw
    # it with vanilla Gen-4 donor textures (hoenn_ground.py). Every chunk
    # binds the SAME texture list, so there is no per-chunk pool assignment.
    used_maps = sorted(set(chunk_owner.values()),
                       key=lambda m: list(origins).index(m))

    def avg_rgb_of(mid, mt):
        im = Image.frombytes("RGB", (16, 16), tile_image(mapdatas, mid, mt))
        return im.resize((1, 1), Image.BOX).getpixel((0, 0))

    sem = hg2.classify_grid(mapdatas, ckey, GW, GH, avg_rgb_of)
    cstats = Counter(sem[z][x] for z in range(GH) for x in range(GW)
                     if ckey[z][x] is not None)
    print("classes:", ", ".join(f"{c}={n}" for c, n in cstats.most_common()))
    ts = hg2.TexSet()
    global_btx = ts.btx
    chunk_tmpl = nsbmd.template(nsbmd.CHUNK_TEMPLATE_PATH)
    tex_names, pal_names, tex_dims, repeat_slots = ts.model_binding(chunk_tmpl.num)
    print(f"global NSBTX: {len(global_btx)} bytes "
          f"({len(ts.slots)} donor textures)")

    # ---- load target NARCs (truncate to post-sinnoh baseline) ------------- #
    land = narc_read(os.path.join(HG, "files/a/0/6/5"))[:BASE["land"]]
    area_data = narc_read(os.path.join(HG, "files/a/0/4/2"))[:BASE["area"]]
    tex_sets = narc_read(os.path.join(HG, "files/a/0/4/4"))[:BASE["tex"]]
    area_build = narc_read(os.path.join(HG, "files/a/0/4/3"))[:BASE["build"]]
    prop_tex = narc_read(os.path.join(HG, "files/a/0/7/0"))[:BASE["prop"]]
    assert len(land) == BASE["land"], "run import_sinnoh.py first"

    # ONE area for the whole region (see module docstring). Its prop archive
    # holds the generated 3D building models + their pltt16 texset.
    build_list, prop_btx = hb.build_props(binfo)
    area_build.append(build_list)
    prop_tex.append(prop_btx)
    hoenn_build_id = len(area_build) - 1
    hoenn_area_id = len(area_data)
    area_data.append(struct.pack("<4H", hoenn_build_id, len(tex_sets), 0xFFFF, 0x0101))
    tex_sets.append(global_btx)
    print(f"area {hoenn_area_id} (single shared), texset {len(tex_sets)-1}, "
          f"prop archive {hoenn_build_id}")

    # ---- generate chunks --------------------------------------------------- #
    models_grid = [[0xFFFF] * CW for _ in range(CH)]
    chunk_verts = {}
    for (cx, cy), mid in sorted(chunk_owner.items(), key=lambda t: (t[0][1], t[0][0])):
        perms = bytearray(0x800)
        for lz in range(32):
            for lx in range(32):
                gx, gz = cx * 32 + lx, cy * 32 + lz
                if gx < GW and gz < GH and ckey[gz][gx] is not None:
                    t, c = perm[gz][gx]
                else:
                    t, c = 0x00, 0x80
                i = (lz * 32 + lx) * 2
                perms[i] = t
                perms[i + 1] = c
        shape_dls, nverts = hg2.emit_chunk(ts, sem, cx, cy, GW, GH)
        chunk_verts[(cx, cy)] = nverts
        model = nsbmd.build_model(shape_dls, tex_dims, tex_names=tex_names,
                                  pal_names=pal_names,
                                  wrap_repeat_slots=repeat_slots,
                                  tmpl=chunk_tmpl)
        member = (struct.pack("<4I", 0x800, 0, len(model), len(FLAT_BDHC))
                  + struct.pack("<HH", 0x1234, 0) + bytes(perms) + model + FLAT_BDHC)
        models_grid[cy][cx] = len(land)
        land.append(member)
    n_chunks = sum(1 for r in models_grid for v in r if v != 0xFFFF)
    vv = sorted(chunk_verts.values())
    worst = max(sum(chunk_verts.get((cx + dx, cy + dy), 0)
                    for dx in (0, 1) for dy in (0, 1))
                for (cx, cy) in chunk_owner)
    print(f"chunks generated: {n_chunks}, land {BASE['land']}->{len(land)}; "
          f"verts min/med/max {vv[0]}/{vv[len(vv)//2]}/{vv[-1]}, "
          f"worst 2x2 window {worst} (DS budget ~6144)")

    # ---- headers + matrix --------------------------------------------------- #
    id_map = {}
    for i, mid in enumerate(used_maps):
        cname = "MAP_APOC_HOENN_" + mid[len("MAP_"):]
        id_map[mid] = (FIRST_NEW_MAP_ID + i, cname)
    headers_grid = [[None] * CW for _ in range(CH)]
    for (cx, cy), mid in chunk_owner.items():
        headers_grid[cy][cx] = id_map[mid][0]
    # nearest-fill for empty cells (safety: header 0 would swap matrices)
    from collections import deque
    q = deque((x, y) for y in range(CH) for x in range(CW) if headers_grid[y][x] is not None)
    while q:
        x, y = q.popleft()
        for dx, dy in ((0, 1), (0, -1), (1, 0), (-1, 0)):
            nx, ny = x + dx, y + dy
            if 0 <= nx < CW and 0 <= ny < CH and headers_grid[ny][nx] is None:
                headers_grid[ny][nx] = headers_grid[y][x]
                q.append((nx, ny))
    mm = MapMatrix(width=CW, height=CH, name="HOENN",
                   models=[models_grid[y][x] for y in range(CH) for x in range(CW)],
                   headers=[headers_grid[y][x] or 0 for y in range(CH) for x in range(CW)],
                   altitudes=[0] * (CW * CH))
    with open(os.path.join(HG, "files/fielddata/mapmatrix/map_matrix", MATRIX_NAME), "wb") as f:
        f.write(mm.serialize())

    # ---- carve causeways (interiors/bridges don't exist here either) ------- #
    seed = find_arrival(GW, GH, perm, origins)
    print("arrival seed:", seed)
    carve(land, models_grid, CW, CH, GW, GH, seed)

    # ---- place 3D building props into the generated chunks ----------------- #
    hb.inject_props(land, models_grid, binfo, CW, CH)

    # ---- C patches ---------------------------------------------------------- #
    defines = [MARK_BEGIN]
    for mid in used_maps:
        hid, cname = id_map[mid]
        defines.append(f"#define {cname:<49} {hid}")
    defines.append(MARK_END)
    patch_file(os.path.join(HG, "include/constants/maps.h"), defines,
               anchor="#endif // POKEHEARTGOLD_CONSTANTS_MAPS_H")
    entries = [MARK_BEGIN]
    for mid in used_maps:
        hid, cname = id_map[mid]
        mtype = ("MAP_TYPE_CITY_TOWN"
                 if mapdatas[mid].json.get("map_type") in ("MAP_TYPE_TOWN", "MAP_TYPE_CITY")
                 else "MAP_TYPE_ROUTE")
        scripts = "NARC_scr_seq_scr_seq_0850_T21_bin" if mid == "MAP_SLATEPORT_CITY" \
            else "NARC_scr_seq_scr_seq_0139_EVERYWHERE_bin"
        events = "NARC_zone_event_492_APOCHOENN_bin" if mid == "MAP_SLATEPORT_CITY" \
            else "NARC_zone_event_000_DUMMY_bin"
        entries.append(f"""    [{cname}] = {{
                        .wildEncounterBank = ENCDATA_NA,
                        .areaDataBank = {hoenn_area_id},
                        .moveModelBank = 15,
                        .worldMapX = 0,
                        .worldMapY = 0,
                        .matrixId = NARC_map_matrix_{MATRIX_NAME.replace('.', '_')},
                        .scriptsBank = {scripts},
                        .scriptHeaderBank = NARC_scr_seq_scr_seq_0399_EVERYWHERE_hdr_bin,
                        .msgBank = NARC_msg_msg_0003_EVERYWHERE_bin,
                        .dayMusicId = SEQ_GS_R_1_30,
                        .nightMusicId = SEQ_GS_R_1_30,
                        .eventsBank = {events},
                        .mapsec = MAPSEC_MYSTERY_ZONE,
                        .areaIcon = 3,
                        .momCallIntroParam = 10,
                        .isKanto = FALSE,
                        .weather = 0,
                        .mapType = {mtype},
                        .cameraType = 0,
                        .followMode = MAP_FOLLOWMODE_ALLOW,
                        .battleBg = BATTLE_BG_GENERAL,
                        .bikeAllowed = TRUE,
                        .runningAllowed_Unused = TRUE,
                        .escapeRopeAllowed = FALSE,
                        .flyAllowed = FALSE,
                        .outgoingCalls = FALSE,
                        .incomingCalls = FALSE,
                        .radioSignal = FALSE,
    }},""")
    entries.append(MARK_END)
    patch_headers_file(os.path.join(HG, "src/data/map_headers.h"), entries)

    # ---- write NARCs -------------------------------------------------------- #
    narc_write(os.path.join(HG, "files/a/0/6/5"), land)
    narc_write(os.path.join(HG, "files/a/0/4/2"), area_data)
    narc_write(os.path.join(HG, "files/a/0/4/4"), tex_sets)
    narc_write(os.path.join(HG, "files/a/0/4/3"), area_build)
    narc_write(os.path.join(HG, "files/a/0/7/0"), prop_tex)

    manifest = {
        "matrix": MATRIX_NAME, "size": [CW, CH],
        "maps": {m: {"id": id_map[m][0], "name": id_map[m][1]} for m in used_maps},
        "arrival": list(seed),
        "origins": {m: origins[m] for m in origins},
    }
    with open(os.path.join(OUT, "hoenn_manifest.json"), "w") as f:
        json.dump(manifest, f, indent=1)
    print(f"done: maps {FIRST_NEW_MAP_ID}..{FIRST_NEW_MAP_ID+len(used_maps)-1}, "
          f"land {len(land)}, areas {len(area_data)}, texsets {len(tex_sets)}")


def find_arrival(GW, GH, perm, origins):
    """An open 5x5 mid-chunk plaza tile in Slateport (ferry warp target).
    The ferry scripts in scr_seq_0850_T21.s hardcode the result — keep in sync."""
    gx, gy, w, h = origins["MAP_SLATEPORT_CITY"]
    def ok(x, z):
        t, c = perm[z][x]
        return c == 0 and t != WATER_HG
    for z in range(gy, gy + h):
        for x in range(gx, gx + w):
            if not (8 <= x % 32 <= 24 and 8 <= z % 32 <= 24):
                continue
            if all(ok(x + dx, z + dz) for dx in range(-2, 3) for dz in range(-2, 3)):
                return (x, z)
    raise SystemExit("no arrival tile found")


def carve(land, models_grid, CW, CH, GW, GH, seed):
    """Same causeway approach as Sinnoh, over the generated grid."""
    from collections import deque
    WATER = {WATER_HG}
    bufs = {}

    def mid_at(x, z):
        if not (0 <= x < CW * 32 and 0 <= z < CH * 32):
            return None
        m = models_grid[z // 32][x // 32]
        return None if m == 0xFFFF else m

    def tile(x, z):
        m = mid_at(x, z)
        if m is None:
            return None, None
        if m not in bufs:
            bufs[m] = bytearray(land[m])
        b = bufs[m]
        i = 20 + ((z % 32) * 32 + (x % 32)) * 2
        return b[i], b[i + 1]

    def carve1(x, z):
        m = mid_at(x, z)
        b = bufs[m]
        i = 20 + ((z % 32) * 32 + (x % 32)) * 2
        b[i] = 0
        b[i + 1] = 0

    def walkable(x, z):
        t, c = tile(x, z)
        return t is not None and not (c & 0x80) and t not in WATER

    def flood(seeds):
        seen = set(s for s in seeds if walkable(*s))
        q = deque(seen)
        while q:
            x, z = q.popleft()
            for dx, dz in ((0, 1), (0, -1), (1, 0), (-1, 0)):
                n = (x + dx, z + dz)
                if n not in seen and walkable(*n):
                    seen.add(n)
                    q.append(n)
        return seen

    assert walkable(*seed), "arrival not walkable"
    carved = 0
    while True:
        reach = flood([seed])
        comp_of, comps = {}, []
        for z0 in range(CH * 32):
            for x0 in range(CW * 32):
                if (x0, z0) in reach or (x0, z0) in comp_of or not walkable(x0, z0):
                    continue
                cid = len(comps)
                tiles_, q = [], deque([(x0, z0)])
                comp_of[(x0, z0)] = cid
                while q:
                    x, z = q.popleft()
                    tiles_.append((x, z))
                    for dx, dz in ((0, 1), (0, -1), (1, 0), (-1, 0)):
                        n = (x + dx, z + dz)
                        if n not in comp_of and n not in reach and walkable(*n):
                            comp_of[n] = cid
                            q.append(n)
                comps.append(tiles_)
        if not any(len(t) >= 250 for t in comps):
            print(f"causeways: done, {carved} carved, {len(reach)} tiles on foot")
            break
        best = None
        for (x, z) in reach:
            for dx, dz in ((0, 1), (0, -1), (1, 0), (-1, 0)):
                nx, nz, gap, water = x + dx, z + dz, 0, 0
                while gap <= 96:
                    t, c = tile(nx, nz)
                    if t is None:
                        break
                    if (c & 0x80) or t in WATER:
                        gap += 1
                        water += 1 if t in WATER else 0
                        nx += dx
                        nz += dz
                        continue
                    if (nx, nz) in reach:
                        break
                    csize = len(comps[comp_of[(nx, nz)]])
                    if gap and csize >= 250:
                        limit = 96 if csize >= 2000 else 48
                        if gap <= limit:
                            score = gap + 6 * water
                            if best is None or score < best[0]:
                                best = (score, x, z, dx, dz, gap)
                    elif csize < 250:
                        gap += 1
                        nx += dx
                        nz += dz
                        continue
                    break
        if best is None:
            print(f"causeways: no more seams, {carved} carved")
            break
        _, x, z, dx, dz, gap = best
        for k in range(1, gap + 1):
            carve1(x + dx * k, z + dz * k)
        carved += 1
        print(f"causeways: carved {gap} at ({x},{z}) d=({dx},{dz})")
    for m, b in bufs.items():
        land[m] = bytes(b)


def patch_file(path, lines, anchor):
    with open(path) as f:
        src = f.read()
    src = strip_block(src)
    block = "\n".join(lines)
    assert anchor in src
    src = src.replace(anchor, block + "\n\n" + anchor)
    with open(path, "w") as f:
        f.write(src)


def patch_headers_file(path, lines):
    with open(path) as f:
        src = f.read()
    src = strip_block(src)
    idx = src.rstrip().rfind("};")
    src = src[:idx] + "\n".join(lines) + "\n" + src[idx:]
    with open(path, "w") as f:
        f.write(src)


def strip_block(src):
    i = src.find(MARK_BEGIN)
    if i < 0:
        return src
    j = src.find(MARK_END) + len(MARK_END)
    while j < len(src) and src[j] == "\n":
        j += 1
    return src[:i] + src[j:]


if __name__ == "__main__":
    main()
