#!/usr/bin/env python3
"""import_hoenn.py - rebuild the Emerald Hoenn overworld inside the HGSS build.

Emerald is GBA, so nothing lifts directly: this generates HGSS assets from the
pokeemerald layout data (run AFTER import_sinnoh.py — it appends to the NARCs
at the counts import_sinnoh leaves behind, and truncates back to them on
re-runs so it is idempotent).

Per 32x32 chunk of the stitched 49-map overworld (emeraldmap.stitch):
  perms  : collision+behavior mapped to HGSS types (grass 0x02, water 0x15,
           ledges/doors/blocked 0x80)
  model  : generated NSBMD (see nsbmd.py) — the chunk-owner map's most common
           tile images drawn as merged rects with repeating 16x16 textures
           from a GLOBAL pool, everything else as quads into ONE global
           content-addressed atlas (2x2 detail blocks baked as supertiles)
  bdhc   : flat template plane (Hoenn v1 is flat)

ONE shared area for the whole region: the engine only renders chunks whose
owner map's area matches the currently-loaded one (crossing a map header
boundary swaps areas and blanks all foreign chunks — the v1 black-chunk bug),
so every Hoenn header points at a single area entry / NSBTX. Per-chunk
texture variety comes from patching the 8 material name slots per chunk
(pool names + 'atlas'); binding resolves them against the shared texture set.
One matrix (map_matrix_0289_HOENN.bin) + 45 headers.
"""
import json
import os
import struct
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from narc import narc_read, narc_write            # noqa: E402
import emeraldmap as em                           # noqa: E402
import nsbmd                                      # noqa: E402
from PIL import Image                             # noqa: E402

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
HG = os.path.join(ROOT, "disasm", "pokeheartgold")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "build")

sys.path.insert(0, os.path.join(ROOT, "tools", "mapeditor"))
from mapdata import MapMatrix                     # noqa: E402

MATRIX_NAME = "map_matrix_0289_HOENN.bin"
FIRST_NEW_MAP_ID = 606
MARK_BEGIN = "// APOC_REGIONPORT HOENN BEGIN (generated by tools/regionport/import_hoenn.py)"
MARK_END = "// APOC_REGIONPORT HOENN END"

# NARC member counts as import_sinnoh.py leaves them (truncate-to on re-run)
BASE = {"land": 852, "area": 119, "tex": 119, "build": 118, "prop": 118}
SHARED_EMPTY_BUILD = 104  # empty build list + dummy prop texture from Sinnoh run

WATER_HG = 0x15
GRASS_HG = 0x02

EM_WATER = set(range(0x10, 0x1B)) | {0x50, 0x51, 0x52, 0x53}
EM_GRASS = {0x02, 0x03, 0x09, 0x24}
EM_BLOCKED_BEH = set(range(0x30, 0x40)) | set(range(0x60, 0x74)) | {0x01}

# flat BDHC template: smallest vanilla Platinum one
with open(os.path.join(ROOT, "disasm/pokeplatinum/res/field/maps/data/map_data_619.bin"), "rb") as f:
    _b = f.read()
    _p, _pr, _mo, _bd = struct.unpack_from("<4I", _b, 0)
    FLAT_BDHC = _b[16 + _p + _pr + _mo:16 + _p + _pr + _mo + _bd]
assert FLAT_BDHC[:4] == b"BDHC"


def stitch_world():
    """Global tile grid: per tile (owner map id, content key, perm bytes)."""
    _, _, origins = em.stitch(["MAP_LITTLEROOT_TOWN", "ALL"])
    GW = max(o[0] + o[2] for o in origins.values())
    GH = max(o[1] + o[3] for o in origins.values())
    owner = [[None] * GW for _ in range(GH)]
    ckey = [[None] * GW for _ in range(GH)]
    perm = [[(0x00, 0x80)] * GW for _ in range(GH)]
    for mid, (gx, gy, w, h) in origins.items():
        m = em.MapData(mid)
        for ty in range(h):
            for tx in range(w):
                v = m.blocks[ty * w + tx]
                mt, coll = v & 0x3FF, (v >> 10) & 3
                _, beh = m.metatile_def(mt)
                if beh in EM_WATER:
                    p = (WATER_HG, 0x00)
                elif coll or beh in EM_BLOCKED_BEH:
                    p = (0x00, 0x80)
                elif beh in EM_GRASS:
                    p = (GRASS_HG, 0x00)
                else:
                    p = (0x00, 0x00)
                owner[gy + ty][gx + tx] = mid
                ckey[gy + ty][gx + tx] = (mid, mt)
                perm[gy + ty][gx + tx] = p
    return GW, GH, owner, ckey, perm, origins


_tile_img_cache = {}


def tile_image(mapdatas, mid, mt):
    """Render one metatile to 16x16 RGB bytes; content-cached."""
    k = (mid, mt)
    if k in _tile_img_cache:
        return _tile_img_cache[k]
    m = mapdatas[mid]
    mdef, _ = m.metatile_def(mt)
    img = Image.new("RGB", (16, 16), (0, 0, 0))
    px = img.load()
    pals = m.palettes()
    if mdef is not None:
        for layer in range(2):
            for sub in range(4):
                v = mdef[layer * 4 + sub]
                tid, hf, vf, pal = v & 0x3FF, v & 0x400, v & 0x800, (v >> 12) & 0xF
                rows = m.subtile_pixels(tid)
                colors = pals[pal] if pal < len(pals) else [(0, 0, 0)] * 16
                ox, oy = (sub % 2) * 8, (sub // 2) * 8
                for ry in range(8):
                    srow = rows[7 - ry] if vf else rows[ry]
                    for rx in range(8):
                        ci = srow[7 - rx] if hf else srow[rx]
                        if layer == 1 and ci == 0:
                            continue
                        px[ox + rx, oy + ry] = colors[ci] if ci < len(colors) else (0, 0, 0)
    data = img.tobytes()
    _tile_img_cache[k] = data
    return data


def greedy_rects(cells):
    cells = set(cells)
    rects = []
    while cells:
        x, z = min(cells, key=lambda t: (t[1], t[0]))
        w = 1
        while (x + w, z) in cells:
            w += 1
        h = 1
        while all((x + i, z + h) in cells for i in range(w)):
            h += 1
        for i in range(w):
            for j in range(h):
                cells.discard((x + i, z + j))
        rects.append((x, z, w, h))
    return rects


def tile_quad(lx, lz, w, h, s0, t0, s1, t1, y=0.0):
    """Chunk-local tile rect -> world quad with texcoords (texels)."""
    x0, z0 = lx * 16 - 256, lz * 16 - 256
    x1, z1 = x0 + w * 16, z0 + h * 16
    return [((x0, y, z0), (s0, t0)), ((x1, y, z0), (s1, t0)),
            ((x1, y, z1), (s1, t1)), ((x0, y, z1), (s0, t1))]


def main():
    os.makedirs(OUT, exist_ok=True)
    print("stitching hoenn...")
    GW, GH, owner, ckey, perm, origins = stitch_world()
    CW, CH = (GW + 31) // 32, (GH + 31) // 32
    print(f"grid {GW}x{GH} tiles -> {CW}x{CH} chunks")
    mapdatas = {mid: em.MapData(mid) for mid in origins}

    # ---- chunk ownership + per-map content stats -------------------------- #
    chunk_owner = {}
    content_of = {}   # (mid, mt) -> content bytes (lazy)
    map_counts = {}   # owner map -> Counter(content)
    for cy in range(CH):
        for cx in range(CW):
            oc = Counter()
            for z in range(cy * 32, min(cy * 32 + 32, GH)):
                for x in range(cx * 32, min(cx * 32 + 32, GW)):
                    if owner[z][x]:
                        oc[owner[z][x]] += 1
            if not oc:
                continue
            chunk_owner[(cx, cy)] = oc.most_common(1)[0][0]
    for (cx, cy), mid in chunk_owner.items():
        cnt = map_counts.setdefault(mid, Counter())
        for z in range(cy * 32, min(cy * 32 + 32, GH)):
            for x in range(cx * 32, min(cx * 32 + 32, GW)):
                k = ckey[z][x]
                if k is None:
                    continue
                c = content_of.get(k)
                if c is None:
                    c = content_of[k] = tile_image(mapdatas, *k)
                cnt[c] += 1

    # ---- global texture planning (one shared area) ------------------------- #
    # A global pool of repeating 16x16 tile textures ('t00'..) covers each
    # map's most common tiles; everything else goes into ONE global atlas
    # ('atlas') as singles or 2x2 supertiles. Chunks pick their 7 pool
    # textures by patched material names.
    used_maps = sorted(map_counts, key=lambda m: list(origins).index(m))
    chunks_of = {}
    for (cx, cy), mid in chunk_owner.items():
        chunks_of.setdefault(mid, []).append((cx, cy))

    def tile_content_at(gx, gz):
        k = ckey[gz][gx]
        if k is None:
            return None
        c = content_of.get(k)
        if c is None:
            c = content_of[k] = tile_image(mapdatas, *k)
        return c

    # Pool textures are chosen PER CHUNK (material names are patched per
    # chunk), so a dense city chunk gets its own dominant tiles as cheap
    # merged-rect geometry even when they're rare region-wide.
    POOL_CAP = 246   # + 'atlas' stays under the 255-entry dict limit
    fill_content = None  # set below: global most common tile (ocean)

    chunk_counts = {}
    for (cx, cy) in chunk_owner:
        cc = Counter()
        for lz in range(32):
            for lx in range(32):
                gx, gz = cx * 32 + lx, cy * 32 + lz
                c = tile_content_at(gx, gz) if gx < GW and gz < GH else None
                if c is not None:
                    cc[c] += 1
        chunk_counts[(cx, cy)] = cc
    global_counts = Counter()
    for cc in chunk_counts.values():
        global_counts.update(cc)
    fill_content = global_counts.most_common(1)[0][0]
    for (cx, cy), cc in chunk_counts.items():
        blanks = 1024 - sum(cc.values())
        if blanks:
            cc[fill_content] += blanks

    votes = Counter()
    chunk_top = {}
    for key, cc in chunk_counts.items():
        top = [c for c, _ in cc.most_common(7)]
        chunk_top[key] = top
        for c in top:
            votes[c] += cc[c]
    votes[fill_content] += 1 << 30   # fill must always be poolable
    ranked = [c for c, _ in votes.most_common(POOL_CAP)]
    pool_name = {c: f"t{i:02x}" for i, c in enumerate(ranked)}
    assigned = {key: [c for c in chunk_top[key] if c in pool_name]
                for key in chunk_counts}

    # global atlas contents: per-chunk detail tiles + 2x2 supertile candidates
    singles_votes = Counter()
    for key, cc in chunk_counts.items():
        a = set(assigned[key])
        for c, n in cc.items():
            if c not in a:
                singles_votes[c] += n
    singles = [c for c, _ in singles_votes.most_common()]
    def super_candidate(quad, a):
        """A 2x2 block worth baking: either all-detail, or an all-pool
        PATTERN (mixed, no 3-of-a-kind — those merge fine as rects)."""
        inpool = sum(1 for c in quad if c in a)
        if inpool == 0:
            return True
        if inpool == 4:
            mc = Counter(quad).most_common(1)[0][1]
            return 1 < len(set(quad)) and mc <= 2
        return False

    super_census = Counter()
    for (cx, cy) in chunk_owner:
        a = set(assigned[(cx, cy)])
        for lz in range(0, 32, 2):
            for lx in range(0, 32, 2):
                quad = []
                for dz in (0, 1):
                    for dx in (0, 1):
                        gx, gz = cx * 32 + lx + dx, cy * 32 + lz + dz
                        c = tile_content_at(gx, gz) if gx < GW and gz < GH else None
                        quad.append(fill_content if c is None else c)
                if super_candidate(quad, a):
                    super_census[tuple(quad)] += 1
    supers = [k for k, n in super_census.most_common() if n >= 3]
    print(f"pool {len(ranked)}, singles {len(singles)}, super candidates "
          f"{len(super_census)} (>=3: {len(supers)})")

    # ---- per-chunk quad counting + window vertex budget --------------------- #
    # The DS renders ~6144 vertices/frame across the 4 loaded chunks; leave
    # headroom for the player/NPCs. Escalate supertile baking until every
    # 2x2 chunk window fits.
    WINDOW_VERT_CAP = 5400

    chunk_over = {}   # (cx,cy) -> {content: pool content} vertex-decimation remaps

    def chunk_geometry(cx, cy, superset, hpairset, vpairset):
        """(pool_lists, super_blocks, hpairs, vpairs, single_cells) for a
        chunk under the current merge sets. Mirrors the emit loop exactly."""
        aslot = {c: k for k, c in enumerate(assigned[(cx, cy)])}
        over = chunk_over.get((cx, cy), {})
        grid_content = [[None] * 32 for _ in range(32)]
        for lz in range(32):
            for lx in range(32):
                gx, gz = cx * 32 + lx, cy * 32 + lz
                c = tile_content_at(gx, gz) if gx < GW and gz < GH else None
                if c is None:
                    c = fill_content
                grid_content[lz][lx] = over.get(c, c)
        # supertiles first, over the FULL grid — this is what merges
        # alternating pool-tile patterns (city pavement) that greedy rects
        # fragment into 1x1s
        sblocks = []
        for lz in range(0, 32, 2):
            for lx in range(0, 32, 2):
                key = (grid_content[lz][lx], grid_content[lz][lx + 1],
                       grid_content[lz + 1][lx], grid_content[lz + 1][lx + 1])
                if None in key or key not in superset:
                    continue
                sblocks.append((lx, lz, key))
                for dz in (0, 1):
                    for dx in (0, 1):
                        grid_content[lz + dz][lx + dx] = None
        by_pool = [[] for _ in range(7)]
        for lz in range(32):
            for lx in range(32):
                c = grid_content[lz][lx]
                if c is None:
                    continue
                ti = aslot.get(c)
                if ti is not None:
                    by_pool[ti].append((lx, lz))
                    grid_content[lz][lx] = None
        hpairs = []
        for lz in range(32):
            lx = 0
            while lx < 31:
                key = (grid_content[lz][lx], grid_content[lz][lx + 1])
                if None not in key and key in hpairset:
                    hpairs.append((lx, lz, key))
                    grid_content[lz][lx] = grid_content[lz][lx + 1] = None
                    lx += 2
                else:
                    lx += 1
        vpairs = []
        for lx in range(32):
            lz = 0
            while lz < 31:
                key = (grid_content[lz][lx], grid_content[lz + 1][lx])
                if None not in key and key in vpairset:
                    vpairs.append((lx, lz, key))
                    grid_content[lz][lx] = grid_content[lz + 1][lx] = None
                    lz += 2
                else:
                    lz += 1
        cells = [(lx, lz, grid_content[lz][lx])
                 for lz in range(32) for lx in range(32)
                 if grid_content[lz][lx] is not None]
        return by_pool, sblocks, hpairs, vpairs, cells

    def chunk_verts(cx, cy, superset, hpairset, vpairset):
        by_pool, sblocks, hp, vp, cells = chunk_geometry(
            cx, cy, superset, hpairset, vpairset)
        nrects = sum(len(greedy_rects(by_pool[k])) for k in range(7))
        return 4 * (nrects + len(sblocks) + len(hp) + len(vp) + len(cells))

    # pair census (horizontal/vertical 2x1 merges of leftover detail cells)
    hpair_census, vpair_census = Counter(), Counter()
    superset0 = set(supers)
    for (cx, cy) in chunk_owner:
        _, _, _, _, cells = chunk_geometry(cx, cy, superset0, set(), set())
        grid = {(lx, lz): c for lx, lz, c in cells}
        for (lx, lz), c in grid.items():
            r = grid.get((lx + 1, lz))
            if r is not None:
                hpair_census[(c, r)] += 1
            d = grid.get((lx, lz + 1))
            if d is not None:
                vpair_census[(c, d)] += 1

    # Merge-cell selection is atlas-byte constrained: a cold pair cell costs
    # 128B and saves 4 verts/occurrence, a cold super cell 256B saving 8.
    # Base sets take the globally hottest; the enforcement loop then spends
    # the remaining byte budget on candidates censused INSIDE failing windows.
    MERGE_BYTE_BUDGET = 48_000
    RESERVE = 24_000   # kept back for window-targeted additions below
    superset, hpairset, vpairset = set(), set(), set()

    def merge_bytes():
        return len(superset) * 256 + (len(hpairset) + len(vpairset)) * 128

    base = ([(n * 8 / 256, 'super', k) for k, n in super_census.items() if n >= 3]
            + [(n * 4 / 128, 'h', k) for k, n in hpair_census.items() if n >= 6]
            + [(n * 4 / 128, 'v', k) for k, n in vpair_census.items() if n >= 6])
    base.sort(reverse=True)
    for _, kind, k in base:
        if merge_bytes() >= MERGE_BYTE_BUDGET - RESERVE:
            break
        {'super': superset, 'h': hpairset, 'v': vpairset}[kind].add(k)

    verts = {c: chunk_verts(*c, superset, hpairset, vpairset) for c in chunk_owner}
    for _round in range(24):
        bad = []
        for (cx, cy) in chunk_owner:
            s = sum(verts.get((cx + dx, cy + dy), 0) for dx in (0, 1) for dy in (0, 1))
            if s > WINDOW_VERT_CAP:
                bad.append((s, cx, cy))
        if not bad:
            break
        if merge_bytes() >= MERGE_BYTE_BUDGET:
            print(f"NOTE: {len(bad)} windows over {WINDOW_VERT_CAP} "
                  f"(worst {max(bad)[0]}) with merge byte budget spent")
            break
        # census merge candidates inside the failing windows only
        bad_chunks = {c for _, cx, cy in bad for c in
                      [(cx + dx, cy + dy) for dx in (0, 1) for dy in (0, 1)]
                      if c in chunk_owner}
        wsc, whc, wvc = Counter(), Counter(), Counter()
        for (cx, cy) in bad_chunks:
            a = set(assigned[(cx, cy)])
            over = chunk_over.get((cx, cy), {})
            # pattern/detail supers over the full grid
            for lz in range(0, 32, 2):
                for lx in range(0, 32, 2):
                    quad = []
                    for dz in (0, 1):
                        for dx in (0, 1):
                            gx, gz = cx * 32 + lx + dx, cy * 32 + lz + dz
                            c = tile_content_at(gx, gz) if gx < GW and gz < GH else None
                            c = fill_content if c is None else c
                            quad.append(over.get(c, c))
                    q = tuple(quad)
                    if q not in superset and super_candidate(q, a):
                        wsc[q] += 1
            # pairs over the leftover detail cells
            _, _, _, _, cells = chunk_geometry(cx, cy, superset, hpairset, vpairset)
            grid = {(lx, lz): c for lx, lz, c in cells}
            for (lx, lz), c in grid.items():
                r = grid.get((lx + 1, lz))
                if r is not None:
                    whc[(c, r)] += 1
                d = grid.get((lx, lz + 1))
                if d is not None:
                    wvc[(c, d)] += 1
        # spend on best savings-per-byte first
        cands = ([(n * 8 / 256, 'super', k) for k, n in wsc.items() if n >= 2]
                 + [(n * 4 / 128, 'h', k) for k, n in whc.items() if n >= 2]
                 + [(n * 4 / 128, 'v', k) for k, n in wvc.items() if n >= 2])
        cands.sort(reverse=True)
        added = 0
        for _, kind, k in cands[:64]:
            if merge_bytes() >= MERGE_BYTE_BUDGET:
                break
            {'super': superset, 'h': hpairset, 'v': vpairset}[kind].add(k)
            added += 1
        if not added:
            print(f"NOTE: {len(bad)} windows over {WINDOW_VERT_CAP} "
                  f"(worst {max(bad)[0]}), no candidates left")
            break
        for c in {c for _, cx, cy in bad for c in
                  [(cx + dx, cy + dy) for dx in (-1, 0, 1) for dy in (-1, 0, 1)]
                  if c in chunk_owner}:
            verts[c] = chunk_verts(*c, superset, hpairset, vpairset)
    # Final decimation: in windows still over cap, remap the worst chunk's
    # rarest detail tiles to its visually-nearest assigned pool tile — a lone
    # detail cell inside a pool expanse dissolves into the merged rect.
    def tile_feat(c):
        im = Image.frombytes("RGB", (16, 16), c).resize((2, 2), Image.LANCZOS)
        return list(im.tobytes())

    exhausted = set()
    for _round in range(400):
        bad = []
        for (cx, cy) in chunk_owner:
            s = sum(verts.get((cx + dx, cy + dy), 0) for dx in (0, 1) for dy in (0, 1))
            if s > WINDOW_VERT_CAP:
                bad.append((s, cx, cy))
        if not bad:
            break
        target = None
        for s, wx, wy in sorted(bad, reverse=True):
            wcands = sorted(
                ((verts[c], c) for c in
                 [(wx + dx, wy + dy) for dx in (0, 1) for dy in (0, 1)]
                 if c in chunk_owner and c not in exhausted and assigned[c]),
                reverse=True)
            if wcands:
                target = wcands[0][1]
                break
        if target is None:
            print(f"NOTE: {len(bad)} windows over cap remain after decimation "
                  f"(worst {max(bad)[0]})")
            break
        _, _, _, _, cells = chunk_geometry(*target, superset, hpairset, vpairset)
        acc = assigned[target]
        over = chunk_over.setdefault(target, {})
        eff = [a for a in acc if a not in over]
        if cells:
            # stage 1: rarest detail tiles -> visually nearest pool tile
            cc = Counter(c for _, _, c in cells)
            afeat = [tile_feat(a) for a in eff or acc]
            src = eff or acc
            for c, _ in sorted(cc.items(), key=lambda t: t[1])[:24]:
                f = tile_feat(c)
                best = min(range(len(src)),
                           key=lambda i: sum((a - b) ** 2 for a, b in zip(afeat[i], f)))
                over[c] = src[best]
        elif len(eff) >= 2:
            # stage 2: merge the two closest pool tiles chunk-wide, collapsing
            # checker patterns into rect-mergeable expanses
            ef = [tile_feat(a) for a in eff]
            bi, bj, bd = 0, 1, None
            for i in range(len(eff)):
                for j in range(i + 1, len(eff)):
                    d = sum((a - b) ** 2 for a, b in zip(ef[i], ef[j]))
                    if bd is None or d < bd:
                        bi, bj, bd = i, j, d
            over[eff[bj]] = eff[bi]
        else:
            exhausted.add(target)
        for c in [(target[0] + dx, target[1] + dy)
                  for dx in (-1, 0, 1) for dy in (-1, 0, 1)]:
            if c in chunk_owner:
                verts[c] = chunk_verts(*c, superset, hpairset, vpairset)
    ndecim = sum(len(v) for v in chunk_over.values())
    supers = sorted(superset, key=lambda k: -super_census[k])
    hpairs = sorted(hpairset, key=lambda k: -hpair_census[k])
    vpairs = sorted(vpairset, key=lambda k: -vpair_census[k])
    vv = sorted(verts.values())
    print(f"supers {len(supers)}, hpairs {len(hpairs)}, vpairs {len(vpairs)} "
          f"({merge_bytes()//1024}KB); decimated {ndecim} tile kinds in "
          f"{len(chunk_over)} chunks; chunk verts min/med/max: "
          f"{vv[0]}/{vv[len(vv)//2]}/{vv[-1]}")
    worst = max(sum(verts.get((cx + dx, cy + dy), 0) for dx in (0, 1) for dy in (0, 1))
                for (cx, cy) in chunk_owner)
    print(f"worst 2x2 window: {worst} (cap {WINDOW_VERT_CAP})")

    # ---- global atlas layout (two resolutions, hard byte budget) ------------ #
    # Uniform-size shelf zones: supers (2x2 tiles), h/v pairs, singles — each
    # at 16px/tile (hot) or 8px/tile (cold). Singles beyond capacity are
    # dropped and remapped to the visually nearest kept cell.
    AW = 512
    TEX_BUDGET = 240_000   # pool + atlas texel bytes; ~2.8x the largest
    pool_bytes = len(ranked) * 256   # vanilla upload — verified in-emu below

    def shelf(pos, items, w, h, rows):
        per = AW // w
        for i, key in enumerate(items):
            pos[key] = ((i % per) * w, rows + (i // per) * h, w, h)
        return rows + ((len(items) + per - 1) // per) * h

    def layout(s16, p16, n16, ncap):
        pos = {}
        rows = shelf(pos, supers[:s16], 32, 32, 0)
        rows = shelf(pos, supers[s16:], 16, 16, rows)
        rows = shelf(pos, hpairs[:p16], 32, 16, rows)
        rows = shelf(pos, hpairs[p16:], 16, 8, rows)
        rows = shelf(pos, vpairs[:p16], 16, 32, rows)
        rows = shelf(pos, vpairs[p16:], 8, 16, rows)
        rows = shelf(pos, singles[:n16], 16, 16, rows)
        rows = shelf(pos, singles[n16:ncap], 8, 8, rows)
        ah = 8
        while ah < rows:
            ah *= 2
        return pos, ah

    s16, p16, n16, ncap = 64, 128, 256, len(singles)
    pos, AH = layout(s16, p16, n16, ncap)
    order = ["n16", "p16", "s16", "ncap"]
    oi = 0
    while AW * AH + pool_bytes > TEX_BUDGET or AH > 512:
        if n16:
            n16 = max(0, n16 - 64)
        elif p16:
            p16 = max(0, p16 - 32)
        elif s16:
            s16 = max(0, s16 - 16)
        elif ncap > 256:
            ncap = max(256, ncap - 128)
        else:
            raise AssertionError(f"atlas cannot fit: {AW}x{AH} + pool {pool_bytes}")
        pos, AH = layout(s16, p16, n16, ncap)
    dropped = singles[ncap:]
    if dropped:
        # remap each dropped single to the visually nearest kept single
        def feat(c):
            im = Image.frombytes("RGB", (16, 16), c).resize((2, 2), Image.LANCZOS)
            return list(im.tobytes())
        kept = singles[:ncap]
        kf = [feat(c) for c in kept]
        for c in dropped:
            f = feat(c)
            best = min(range(len(kept)),
                       key=lambda i: sum((a - b) ** 2 for a, b in zip(kf[i], f)))
            pos[c] = pos[kept[best]]
        print(f"dropped {len(dropped)} rare singles (remapped to nearest)")
    print(f"atlas {AW}x{AH} ({AW*AH//1024}KB) + pool {pool_bytes//1024}KB; "
          f"tiers s16={s16} p16={p16} n16={n16} kept={ncap}/{len(singles)}")

    # ---- build the ONE global NSBTX (pool + atlas, one 256-color palette) --- #
    strip = Image.new("RGB", (AW, AH + 16 * ((len(ranked) + 31) // 32)), (0, 0, 0))
    drawn = set()
    for c, (px, py, w, h) in pos.items():
        if (px, py) in drawn:      # remapped duplicates share a cell
            continue
        drawn.add((px, py))
        if isinstance(c, tuple) and len(c) == 4:      # 2x2 supertile
            im = Image.new("RGB", (32, 32))
            for i, sub in enumerate(c):
                im.paste(Image.frombytes("RGB", (16, 16), sub),
                         ((i % 2) * 16, (i // 2) * 16))
        elif isinstance(c, tuple):                    # pair: (left,right)/(top,bottom)
            horiz = w >= h
            im = Image.new("RGB", (32, 16) if horiz else (16, 32))
            im.paste(Image.frombytes("RGB", (16, 16), c[0]), (0, 0))
            im.paste(Image.frombytes("RGB", (16, 16), c[1]),
                     (16, 0) if horiz else (0, 16))
        else:
            im = Image.frombytes("RGB", (16, 16), c)
        if im.size != (w, h):
            im = im.resize((w, h), Image.LANCZOS)
        strip.paste(im, (px, py))
    for i, c in enumerate(ranked):     # pool tiles below the atlas
        strip.paste(Image.frombytes("RGB", (16, 16), c),
                    ((i % 32) * 16, AH + (i // 32) * 16))
    q = strip.quantize(colors=256)
    pal = (q.getpalette() or [])[:768]
    pal += [0] * (768 - len(pal))
    qpx = q.load()
    atlas_tex = bytes(qpx[x, y] for y in range(AH) for x in range(AW))
    pool_tex = []
    for i in range(len(ranked)):
        ox, oy = (i % 32) * 16, AH + (i // 32) * 16
        pool_tex.append(bytes(qpx[ox + x, oy + y] for y in range(16) for x in range(16)))
    palbin = bytearray()
    for i in range(256):
        r, g, b = pal[i * 3] >> 3, pal[i * 3 + 1] >> 3, pal[i * 3 + 2] >> 3
        palbin += struct.pack("<H", r | (g << 5) | (b << 10))
    global_btx = nsbmd.build_btx_named(
        [(pool_name[c], 16, 16, pool_tex[i]) for i, c in enumerate(ranked)]
        + [("atlas", AW, AH, atlas_tex)],
        [("glb_pl", bytes(palbin))])
    print(f"global NSBTX: {len(global_btx)} bytes")

    # ---- load target NARCs (truncate to post-sinnoh baseline) ------------- #
    land = narc_read(os.path.join(HG, "files/a/0/6/5"))[:BASE["land"]]
    area_data = narc_read(os.path.join(HG, "files/a/0/4/2"))[:BASE["area"]]
    tex_sets = narc_read(os.path.join(HG, "files/a/0/4/4"))[:BASE["tex"]]
    area_build = narc_read(os.path.join(HG, "files/a/0/4/3"))[:BASE["build"]]
    prop_tex = narc_read(os.path.join(HG, "files/a/0/7/0"))[:BASE["prop"]]
    assert len(land) == BASE["land"], "run import_sinnoh.py first"

    # ONE area for the whole region (see module docstring)
    hoenn_area_id = len(area_data)
    area_data.append(struct.pack("<4H", SHARED_EMPTY_BUILD, len(tex_sets), 0xFFFF, 0x0101))
    tex_sets.append(global_btx)
    print(f"area {hoenn_area_id} (single shared), texset {len(tex_sets)-1}")

    # ---- generate chunks --------------------------------------------------- #
    models_grid = [[0xFFFF] * CW for _ in range(CH)]
    fill_name = pool_name[ranked[0]]
    for (cx, cy), mid in sorted(chunk_owner.items(), key=lambda t: (t[0][1], t[0][0])):
        by_pool, sblocks, hp, vp, cells = chunk_geometry(
            cx, cy, superset, hpairset, vpairset)
        perms = bytearray(0x800)
        for lz in range(32):
            for lx in range(32):
                gx, gz = cx * 32 + lx, cy * 32 + lz
                if gx < GW and gz < GH and ckey[gz][gx] is not None:
                    t, c = perm[gz][gx]
                else:
                    t, c = 0x00, 0x80
                i = (lz * 32 + lx) * 2
                perms[i] = t
                perms[i + 1] = c
        dq = []
        for lx, lz, key in sblocks:
            px, py, w, h = pos[key]
            dq.append(tile_quad(lx, lz, 2, 2, px, py, px + w, py + h))
        for lx, lz, key in hp:
            px, py, w, h = pos[key]
            dq.append(tile_quad(lx, lz, 2, 1, px, py, px + w, py + h))
        for lx, lz, key in vp:
            px, py, w, h = pos[key]
            dq.append(tile_quad(lx, lz, 1, 2, px, py, px + w, py + h))
        for lx, lz, c in cells:
            p = pos.get(c)
            if p is None:
                continue
            px, py, w, h = p
            dq.append(tile_quad(lx, lz, 1, 1, px, py, px + w, py + h))
        shape_dls = []
        for k in range(7):
            quads = [tile_quad(x, z, w, h, 0, 0, w * 16, h * 16)
                     for (x, z, w, h) in greedy_rects(by_pool[k])]
            shape_dls.append(nsbmd.quad_dl(quads))
        shape_dls.append(nsbmd.quad_dl(dq))
        names = [pool_name[c] for c in assigned[(cx, cy)]]
        names += [fill_name] * (7 - len(names))
        names.append("atlas")
        model = nsbmd.build_model(shape_dls, [(16, 16)] * 7 + [(AW, AH)],
                                  tex_names=names, pal_names=["glb_pl"] * 8)
        member = (struct.pack("<4I", 0x800, 0, len(model), len(FLAT_BDHC))
                  + struct.pack("<HH", 0x1234, 0) + bytes(perms) + model + FLAT_BDHC)
        models_grid[cy][cx] = len(land)
        land.append(member)
    n_chunks = sum(1 for r in models_grid for v in r if v != 0xFFFF)
    print(f"chunks generated: {n_chunks}, land {BASE['land']}->{len(land)}")

    # ---- headers + matrix --------------------------------------------------- #
    id_map = {}
    for i, mid in enumerate(used_maps):
        cname = "MAP_APOC_HOENN_" + mid[len("MAP_"):]
        id_map[mid] = (FIRST_NEW_MAP_ID + i, cname)
    headers_grid = [[None] * CW for _ in range(CH)]
    for (cx, cy), mid in chunk_owner.items():
        headers_grid[cy][cx] = id_map[mid][0]
    # nearest-fill for empty cells (safety: header 0 would swap matrices)
    from collections import deque
    q = deque((x, y) for y in range(CH) for x in range(CW) if headers_grid[y][x] is not None)
    while q:
        x, y = q.popleft()
        for dx, dy in ((0, 1), (0, -1), (1, 0), (-1, 0)):
            nx, ny = x + dx, y + dy
            if 0 <= nx < CW and 0 <= ny < CH and headers_grid[ny][nx] is None:
                headers_grid[ny][nx] = headers_grid[y][x]
                q.append((nx, ny))
    mm = MapMatrix(width=CW, height=CH, name="HOENN",
                   models=[models_grid[y][x] for y in range(CH) for x in range(CW)],
                   headers=[headers_grid[y][x] or 0 for y in range(CH) for x in range(CW)],
                   altitudes=[0] * (CW * CH))
    with open(os.path.join(HG, "files/fielddata/mapmatrix/map_matrix", MATRIX_NAME), "wb") as f:
        f.write(mm.serialize())

    # ---- carve causeways (interiors/bridges don't exist here either) ------- #
    seed = find_arrival(GW, GH, perm, origins)
    print("arrival seed:", seed)
    carve(land, models_grid, CW, CH, GW, GH, seed)

    # ---- C patches ---------------------------------------------------------- #
    defines = [MARK_BEGIN]
    for mid in used_maps:
        hid, cname = id_map[mid]
        defines.append(f"#define {cname:<49} {hid}")
    defines.append(MARK_END)
    patch_file(os.path.join(HG, "include/constants/maps.h"), defines,
               anchor="#endif // POKEHEARTGOLD_CONSTANTS_MAPS_H")
    entries = [MARK_BEGIN]
    for mid in used_maps:
        hid, cname = id_map[mid]
        mtype = ("MAP_TYPE_CITY_TOWN"
                 if mapdatas[mid].json.get("map_type") in ("MAP_TYPE_TOWN", "MAP_TYPE_CITY")
                 else "MAP_TYPE_ROUTE")
        scripts = "NARC_scr_seq_scr_seq_0850_T21_bin" if mid == "MAP_SLATEPORT_CITY" \
            else "NARC_scr_seq_scr_seq_0139_EVERYWHERE_bin"
        events = "NARC_zone_event_492_APOCHOENN_bin" if mid == "MAP_SLATEPORT_CITY" \
            else "NARC_zone_event_000_DUMMY_bin"
        entries.append(f"""    [{cname}] = {{
                        .wildEncounterBank = ENCDATA_NA,
                        .areaDataBank = {hoenn_area_id},
                        .moveModelBank = 15,
                        .worldMapX = 0,
                        .worldMapY = 0,
                        .matrixId = NARC_map_matrix_{MATRIX_NAME.replace('.', '_')},
                        .scriptsBank = {scripts},
                        .scriptHeaderBank = NARC_scr_seq_scr_seq_0399_EVERYWHERE_hdr_bin,
                        .msgBank = NARC_msg_msg_0003_EVERYWHERE_bin,
                        .dayMusicId = SEQ_GS_R_1_30,
                        .nightMusicId = SEQ_GS_R_1_30,
                        .eventsBank = {events},
                        .mapsec = MAPSEC_MYSTERY_ZONE,
                        .areaIcon = 3,
                        .momCallIntroParam = 10,
                        .isKanto = FALSE,
                        .weather = 0,
                        .mapType = {mtype},
                        .cameraType = 0,
                        .followMode = MAP_FOLLOWMODE_ALLOW,
                        .battleBg = BATTLE_BG_GENERAL,
                        .bikeAllowed = TRUE,
                        .runningAllowed_Unused = TRUE,
                        .escapeRopeAllowed = FALSE,
                        .flyAllowed = FALSE,
                        .outgoingCalls = FALSE,
                        .incomingCalls = FALSE,
                        .radioSignal = FALSE,
    }},""")
    entries.append(MARK_END)
    patch_headers_file(os.path.join(HG, "src/data/map_headers.h"), entries)

    # ---- write NARCs -------------------------------------------------------- #
    narc_write(os.path.join(HG, "files/a/0/6/5"), land)
    narc_write(os.path.join(HG, "files/a/0/4/2"), area_data)
    narc_write(os.path.join(HG, "files/a/0/4/4"), tex_sets)
    narc_write(os.path.join(HG, "files/a/0/4/3"), area_build)
    narc_write(os.path.join(HG, "files/a/0/7/0"), prop_tex)

    manifest = {
        "matrix": MATRIX_NAME, "size": [CW, CH],
        "maps": {m: {"id": id_map[m][0], "name": id_map[m][1]} for m in used_maps},
        "arrival": list(seed),
        "origins": {m: origins[m] for m in origins},
    }
    with open(os.path.join(OUT, "hoenn_manifest.json"), "w") as f:
        json.dump(manifest, f, indent=1)
    print(f"done: maps {FIRST_NEW_MAP_ID}..{FIRST_NEW_MAP_ID+len(used_maps)-1}, "
          f"land {len(land)}, areas {len(area_data)}, texsets {len(tex_sets)}")


def find_arrival(GW, GH, perm, origins):
    """An open 5x5 mid-chunk plaza tile in Slateport (ferry warp target).
    The ferry scripts in scr_seq_0850_T21.s hardcode the result — keep in sync."""
    gx, gy, w, h = origins["MAP_SLATEPORT_CITY"]
    def ok(x, z):
        t, c = perm[z][x]
        return c == 0 and t != WATER_HG
    for z in range(gy, gy + h):
        for x in range(gx, gx + w):
            if not (8 <= x % 32 <= 24 and 8 <= z % 32 <= 24):
                continue
            if all(ok(x + dx, z + dz) for dx in range(-2, 3) for dz in range(-2, 3)):
                return (x, z)
    raise SystemExit("no arrival tile found")


def carve(land, models_grid, CW, CH, GW, GH, seed):
    """Same causeway approach as Sinnoh, over the generated grid."""
    from collections import deque
    WATER = {WATER_HG}
    bufs = {}

    def mid_at(x, z):
        if not (0 <= x < CW * 32 and 0 <= z < CH * 32):
            return None
        m = models_grid[z // 32][x // 32]
        return None if m == 0xFFFF else m

    def tile(x, z):
        m = mid_at(x, z)
        if m is None:
            return None, None
        if m not in bufs:
            bufs[m] = bytearray(land[m])
        b = bufs[m]
        i = 20 + ((z % 32) * 32 + (x % 32)) * 2
        return b[i], b[i + 1]

    def carve1(x, z):
        m = mid_at(x, z)
        b = bufs[m]
        i = 20 + ((z % 32) * 32 + (x % 32)) * 2
        b[i] = 0
        b[i + 1] = 0

    def walkable(x, z):
        t, c = tile(x, z)
        return t is not None and not (c & 0x80) and t not in WATER

    def flood(seeds):
        seen = set(s for s in seeds if walkable(*s))
        q = deque(seen)
        while q:
            x, z = q.popleft()
            for dx, dz in ((0, 1), (0, -1), (1, 0), (-1, 0)):
                n = (x + dx, z + dz)
                if n not in seen and walkable(*n):
                    seen.add(n)
                    q.append(n)
        return seen

    assert walkable(*seed), "arrival not walkable"
    carved = 0
    while True:
        reach = flood([seed])
        comp_of, comps = {}, []
        for z0 in range(CH * 32):
            for x0 in range(CW * 32):
                if (x0, z0) in reach or (x0, z0) in comp_of or not walkable(x0, z0):
                    continue
                cid = len(comps)
                tiles_, q = [], deque([(x0, z0)])
                comp_of[(x0, z0)] = cid
                while q:
                    x, z = q.popleft()
                    tiles_.append((x, z))
                    for dx, dz in ((0, 1), (0, -1), (1, 0), (-1, 0)):
                        n = (x + dx, z + dz)
                        if n not in comp_of and n not in reach and walkable(*n):
                            comp_of[n] = cid
                            q.append(n)
                comps.append(tiles_)
        if not any(len(t) >= 250 for t in comps):
            print(f"causeways: done, {carved} carved, {len(reach)} tiles on foot")
            break
        best = None
        for (x, z) in reach:
            for dx, dz in ((0, 1), (0, -1), (1, 0), (-1, 0)):
                nx, nz, gap, water = x + dx, z + dz, 0, 0
                while gap <= 96:
                    t, c = tile(nx, nz)
                    if t is None:
                        break
                    if (c & 0x80) or t in WATER:
                        gap += 1
                        water += 1 if t in WATER else 0
                        nx += dx
                        nz += dz
                        continue
                    if (nx, nz) in reach:
                        break
                    csize = len(comps[comp_of[(nx, nz)]])
                    if gap and csize >= 250:
                        limit = 96 if csize >= 2000 else 48
                        if gap <= limit:
                            score = gap + 6 * water
                            if best is None or score < best[0]:
                                best = (score, x, z, dx, dz, gap)
                    elif csize < 250:
                        gap += 1
                        nx += dx
                        nz += dz
                        continue
                    break
        if best is None:
            print(f"causeways: no more seams, {carved} carved")
            break
        _, x, z, dx, dz, gap = best
        for k in range(1, gap + 1):
            carve1(x + dx * k, z + dz * k)
        carved += 1
        print(f"causeways: carved {gap} at ({x},{z}) d=({dx},{dz})")
    for m, b in bufs.items():
        land[m] = bytes(b)


def patch_file(path, lines, anchor):
    with open(path) as f:
        src = f.read()
    src = strip_block(src)
    block = "\n".join(lines)
    assert anchor in src
    src = src.replace(anchor, block + "\n\n" + anchor)
    with open(path, "w") as f:
        f.write(src)


def patch_headers_file(path, lines):
    with open(path) as f:
        src = f.read()
    src = strip_block(src)
    idx = src.rstrip().rfind("};")
    src = src[:idx] + "\n".join(lines) + "\n" + src[idx:]
    with open(path, "w") as f:
        f.write(src)


def strip_block(src):
    i = src.find(MARK_BEGIN)
    if i < 0:
        return src
    j = src.find(MARK_END) + len(MARK_END)
    while j < len(src) and src[j] == "\n":
        j += 1
    return src[:i] + src[j:]


if __name__ == "__main__":
    main()
