#!/usr/bin/env python3
"""sinnoh_life.py - add interactivity to the ported Sinnoh region.

Run AFTER import_sinnoh.py (reads build/sinnoh_manifest.json). Generates,
from Platinum's own event/encounter data (coordinates transfer 1:1 because
the Sinnoh matrix preserves Platinum's 30x30 layout):

  1. zone_event JSONs 494_APOCSIN_<MAP>.json -- every always-visible Platinum
     NPC (sprites remapped to HGSS equivalents, movement remapped, generic
     Apocrypha dialogue) + PC/Mart door warps. Item balls, signs, berry
     soil, story-flagged actors are skipped.
  2. Interior clones: per city with a PC/Mart door, a new map header that
     reuses the Cherrygrove PC/Mart map (matrix/land/scripts/msg -- so the
     nurse heals and the shop sells), with cloned events whose exit warp
     returns to the right Sinnoh city. Header ids from FIRST_INTERIOR_ID.
  3. scr_seq_0967_APOCSIN.s + msg_0830_APOCSIN.gmm -- generic NPC dialogue
     scripts (script 0 = the Canalave->Cherrygrove return ferry, moved here
     from T21's bank so Sinnoh maps can own their scriptsBank).
  4. Wild encounter rows appended to g_/s_enc_data.csv from Platinum's
     encounter JSONs (time-of-day slots 2/3 swapped per DPPt convention;
     ruby/sapphire dual-slot species feed the Hoenn Sound radio slots,
     radar species the Sinnoh Sound slots).
  5. map_headers.h SINNOH block updated in place (events/scripts/encounter
     banks) + new INTERIORS marker block; maps.h interior defines.
  6. build/sinnoh_overrides.json so a future import_sinnoh.py re-run can
     restore the same per-map banks.

Idempotent: re-running regenerates all its own files (494_APOCSIN_*/5xx
zone events, marker blocks, APOCSIN_ CSV rows).
"""
import json
import os
import re
import sys
from collections import OrderedDict

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
HG = os.path.join(ROOT, "disasm", "pokeheartgold")
PLAT = os.path.join(ROOT, "disasm", "pokeplatinum")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "build")
ZE_DIR = os.path.join(HG, "files/fielddata/eventdata/zone_event")

FIRST_INTERIOR_ID = 670
OUTDOOR_ZE_BASE = 494          # 494_APOCSIN_<NAME>.json
INTERIOR_ZE_BASE = 560         # 560_APOCSIN_PC_<CITY>.json
MARK_BEGIN = "// APOC_SINNOH_LIFE INTERIORS BEGIN (generated by tools/regionport/sinnoh_life.py)"
MARK_END = "// APOC_SINNOH_LIFE INTERIORS END"

# ---- sprite mapping: Platinum OBJ_EVENT_GFX_* -> HGSS SPRITE_* ------------- #
SKIP_GFX_SUBSTR = (
    "POKEBALL", "UNK_", "SIGN", "VENT", "CUT_TREE", "ROCK_SMASH",
    "STRENGTH_BOULDER", "BOLLARD", "DOOR", "GATE", "TRAPDOOR", "STAIRS",
)
SPRITE_MAP = {
    "ACE_TRAINER_M": "SPRITE_GSMAN3", "ACE_TRAINER_F": "SPRITE_GSWOMAN3",
    "ACE_TRAINER_SNOW_M": "SPRITE_BOARDER", "ACE_TRAINER_SNOW_F": "SPRITE_SKIERW",
    "FISHERMAN": "SPRITE_FISHING", "BLACK_BELT": "SPRITE_GSFIGHTER",
    "GRUNT_M": "SPRITE_ROCKETM", "GRUNT_F": "SPRITE_ROCKETW",
    "YOUNGSTER": "SPRITE_GSBOY2", "SCHOOL_KID_M": "SPRITE_GSBOY3",
    "SCHOOL_KID_F": "SPRITE_GSGIRL3", "NINJA_BOY": "SPRITE_BOZU",
    "LASS": "SPRITE_GSGIRL2", "BATTLE_GIRL": "SPRITE_GSGIRL3",
    "SAILOR": "SPRITE_SEAMAN", "SWIMMER_M": "SPRITE_GSSWIMMERM",
    "SWIMMER_F": "SPRITE_GSSWIMMERW", "COLLECTOR": "SPRITE_MANIA",
    "POKEMON_BREEDER_M": "SPRITE_GSMAN2", "POKEMON_BREEDER_F": "SPRITE_GSWOMAN2",
    "HIKER": "SPRITE_MOUNT", "JOGGER": "SPRITE_SPORTSMAN",
    "POLICEMAN": "SPRITE_POLICEMAN", "BEAUTY": "SPRITE_GSWOMAN6",
    "TWIN": "SPRITE_GSGIRL1", "GUITARIST": "SPRITE_GANG",
    "PSYCHIC_M": "SPRITE_MYSTERY", "PSYCHIC_F": "SPRITE_ITAKO",
    "PSYCHIC": "SPRITE_MYSTERY", "RUIN_MANIAC": "SPRITE_EXPLORE",
    "EXPERT_M": "SPRITE_GSOLDMAN1", "EXPERT_F": "SPRITE_GSOLDWOMAN1",
    "WORKER": "SPRITE_WORKMAN", "CASHIER_F": "SPRITE_SHOPW1",
    "CASHIER_M": "SPRITE_SHOPM1", "CLERK_M": "SPRITE_SHOPM1",
    "CLERK_F": "SPRITE_SHOPW1", "POKEFAN_M": "SPRITE_GSBIGMAN",
    "POKEFAN_F": "SPRITE_MIDDLEWOMAN1", "GENTLEMAN": "SPRITE_GSGENTLEMAN",
    "SOCIALITE": "SPRITE_LADY", "MADAME": "SPRITE_LADY",
    "OLD_MAN": "SPRITE_GSOLDMAN1", "OLD_WOMAN": "SPRITE_GSOLDWOMAN1",
    "BOY_1": "SPRITE_GSBOY1", "BOY_2": "SPRITE_GSBOY2", "BOY_3": "SPRITE_GSBOY3",
    "GIRL_1": "SPRITE_GSGIRL1", "GIRL_2": "SPRITE_GSGIRL2", "GIRL_3": "SPRITE_GSGIRL3",
    "MAN_1": "SPRITE_GSMAN1", "MAN_2": "SPRITE_GSMAN2", "MAN_3": "SPRITE_GSMAN3",
    "WOMAN_1": "SPRITE_GSWOMAN1", "WOMAN_2": "SPRITE_GSWOMAN2",
    "WOMAN_3": "SPRITE_GSWOMAN3", "BARRY": "SPRITE_GSRIVEL",
    "TEALA": "SPRITE_PCWOMAN1", "IDOL": "SPRITE_IDOL", "CLOWN": "SPRITE_CLOWN",
    "ARTIST": "SPRITE_ARTIST", "REPORTER": "SPRITE_REPORTER",
    "CAMERAMAN": "SPRITE_CAMERAMAN", "WAITER": "SPRITE_WAITER",
    "WAITRESS": "SPRITE_WAITRESS", "MAID": "SPRITE_MAID",
    "DOCTOR": "SPRITE_DOCTOR", "SCIENTIST_M": "SPRITE_ASSISTANTM",
    "SCIENTIST_F": "SPRITE_ASSISTANTW", "SCIENTIST": "SPRITE_ASSISTANTM",
    "FARMER": "SPRITE_FARMER", "COWGIRL": "SPRITE_COWGIRL",
    "RICH_BOY": "SPRITE_GSBOY1", "DRAGON_TAMER": "SPRITE_GSFIGHTER",
    "ROUGHNECK": "SPRITE_GANG", "BIRD_KEEPER": "SPRITE_CAMPBOY",
    "BUG_CATCHER": "SPRITE_CAMPBOY", "CAMPER": "SPRITE_CAMPBOY",
    "PICNICKER": "SPRITE_PICNICGIRL", "CYCLIST_M": "SPRITE_CYCLEM",
    "CYCLIST_F": "SPRITE_CYCLEW", "SKIER_F": "SPRITE_SKIERW",
    "SKIER_M": "SPRITE_BOARDER", "TUBER_M": "SPRITE_GSBABYBOY1",
    "TUBER_F": "SPRITE_GSBABYGIRL1", "PRESCHOOLER_M": "SPRITE_GSBABYBOY1",
    "PRESCHOOLER_F": "SPRITE_GSBABYGIRL1", "LADY": "SPRITE_LADY",
    "VETERAN": "SPRITE_GSOLDMAN1", "GALACTIC_BOSS": "SPRITE_BADMAN",
    "COMMANDER_M": "SPRITE_RKANBUM", "COMMANDER_F": "SPRITE_RKANBUW",
}
FALLBACK_SPRITES = ["SPRITE_GSMAN1", "SPRITE_GSWOMAN1", "SPRITE_GSBOY1",
                    "SPRITE_GSGIRL1", "SPRITE_MIDDLEMAN1", "SPRITE_MIDDLEWOMAN1"]

# ---- generic dialogue ------------------------------------------------------ #
# (category, text). Categories: any, city, route, trainer, kid, elder, water
LINES = [
    ("any", "Sinnoh, at last! You came over on the\\nCherrygrove ferry too, didn’t you?"),
    ("any", "Strange days. Trainers from Johto and\\nKanto just walking around Sinnoh…\\fI don’t mind it one bit, honestly."),
    ("city", "This city’s barely changed since I was\\nlittle. The rest of the world sure has."),
    ("city", "The Pokémon Center will patch up your\\nteam. The clerk at the mart still\\fstocks the good stuff, too."),
    ("city", "Sailors say you can walk the coast for\\ndays and never leave Sinnoh.\\fI say let them try HOENN’s beaches."),
    ("route", "Watch the tall grass around here.\\nThe wild Pokémon aren’t shy."),
    ("route", "I’ve been walking this route for years.\\nStill find new Pokémon every season."),
    ("route", "A storm’s always brewing off Mt. Coronet.\\nDress warm, trainer."),
    ("trainer", "My team’s in top shape--but league rules\\nsay exhibition matches only this month.\\fCome find me when the season opens!"),
    ("trainer", "I used to battle every trainer who made\\neye contact. I’m retired now.\\fMostly."),
    ("kid", "A lady told me the ferry goes all the\\nway to JOHTO! That’s across the SEA!"),
    ("kid", "I’m gonna catch a STARLY and name it\\nMister Feathers!"),
    ("elder", "In my day, crossing regions took weeks\\nby boat. Now look at you youngsters."),
    ("elder", "The old legends of Sinnoh live in these\\nmountains. Tread kindly, child."),
    ("water", "The current’s gentle today. A strong\\nswimmer could cross to the far shore."),
    ("water", "Me? I just like watching the water.\\nThe Pokémon under there like it too."),
]
KID_SPRITES = {"SPRITE_GSBOY1", "SPRITE_GSBOY2", "SPRITE_GSBOY3", "SPRITE_GSGIRL1",
               "SPRITE_GSGIRL2", "SPRITE_GSGIRL3", "SPRITE_BOZU", "SPRITE_GSBABYBOY1",
               "SPRITE_GSBABYGIRL1", "SPRITE_CAMPBOY", "SPRITE_PICNICGIRL"}
ELDER_SPRITES = {"SPRITE_GSOLDMAN1", "SPRITE_GSOLDWOMAN1", "SPRITE_CHOUROU"}
WATER_SPRITES = {"SPRITE_GSSWIMMERM", "SPRITE_GSSWIMMERW", "SPRITE_FISHING", "SPRITE_SEAMAN"}


def line_index_for(sprite, is_trainer, is_city, salt):
    cats = ["any"]
    if is_trainer:
        cats = ["trainer", "any"]
    elif sprite in KID_SPRITES:
        cats = ["kid", "any"]
    elif sprite in ELDER_SPRITES:
        cats = ["elder", "any"]
    elif sprite in WATER_SPRITES:
        cats = ["water", "any"]
    elif is_city:
        cats = ["city", "any"]
    else:
        cats = ["route", "any"]
    idxs = [i for i, (c, _) in enumerate(LINES) if c in cats]
    return idxs[salt % len(idxs)]


DIRS = {"NORTH": 0, "SOUTH": 1, "WEST": 2, "EAST": 3, "LEFT": 2, "RIGHT": 3}


def convert_movement(o):
    """Platinum object -> (movement, facing, xRange, yRange) or None to skip."""
    mt = o["movement_type"].replace("MOVEMENT_TYPE_", "")
    rx = max(int(o.get("movement_range_x", 1)), 1)
    rz = max(int(o.get("movement_range_z", 1)), 1)
    facing = int(o.get("initial_dir", 0)) & 3
    if mt in ("BERRY_SOIL", "FOLLOW_PARTNER_TRAINER") or mt.startswith("DISGUISE"):
        return None
    if mt == "WANDER_AROUND":
        return 3, facing, rx, rz
    if mt == "WANDER_WEST_AND_EAST":
        return 5, facing, rx, 0
    if mt == "WANDER_NORTH_AND_SOUTH":
        return 4, facing, 0, rz
    if mt == "WALK_BACK_AND_FORTH":
        return (5, facing, rx, 0) if rx >= rz else (4, facing, 0, rz)
    if mt.startswith("WALK_") or mt.startswith("ROTATE") or mt == "LOOK_AROUND":
        return 2, facing, 0, 0
    if mt == "NONE":
        return 0, facing, 0, 0
    if mt.startswith("LOOK_"):
        parts = mt[5:].split("_AND_")[0].split("_")
        d = DIRS.get(parts[0], facing)
        return 0, d, 0, 0
    return 0, facing, 0, 0


def map_sprite(gfx):
    name = gfx.replace("OBJ_EVENT_GFX_", "")
    for s in SKIP_GFX_SUBSTR:
        if s in name:
            return None
    if name in SPRITE_MAP:
        return SPRITE_MAP[name]
    # heuristic: unknown people get a stable generic sprite
    return FALLBACK_SPRITES[hash(name) % len(FALLBACK_SPRITES)]


def parse_plat_header_field(hdrs, h, name):
    i = hdrs.find("[" + h + "]")
    seg = hdrs[i:hdrs.find("}", i)]
    m = re.search(r"\." + name + r"\s*=\s*([^,\n]+)", seg)
    return m.group(1).strip() if m else None


def load_platinum(man):
    hdrs = open(os.path.join(PLAT, "include/data/map_headers.h")).read()
    order = [l.strip() for l in open(os.path.join(PLAT, "res/field/events/zone_event.order")) if l.strip()]
    encorder = [l.strip().replace(".bin", "") for l in
                open(os.path.join(PLAT, "res/field/encounters/encounters.order")) if l.strip()]
    plat = {}
    for h in man["maps"]:
        ev = parse_plat_header_field(hdrs, h, "eventsArchiveID")
        evfile = order[int(ev, 0)] if re.match(r"^(0x)?\d+$", ev) else ev
        events = json.load(open(os.path.join(PLAT, "res/field/events", evfile + ".json")))
        enc = parse_plat_header_field(hdrs, h, "wildEncountersArchiveID")
        encounters = None
        if enc is not None:
            if re.match(r"^(0x[0-9a-fA-F]+|\d+)$", enc):
                e = int(enc, 0)
                encfile = encorder[e] if e != 0xFFFF and e < len(encorder) else None
            else:
                encfile = enc
            if encfile:
                encounters = json.load(open(os.path.join(PLAT, "res/field/encounters", encfile + ".json")))
        mtype = parse_plat_header_field(hdrs, h, "mapType")
        plat[h] = {"events": events, "enc": encounters, "is_city": mtype == "0x1"}
    return plat


# ---- zone_event emission --------------------------------------------------- #

def build_outdoor_events(man, plat, interiors, door_map, sign_scripts,
                         porter_script):
    """Returns {header_name: (filename, json_dict, warp_map)} where warp_map
    maps interior key -> warp index in this file. sign_scripts maps header
    name -> scriptId for the map's signpost text."""
    result = {}
    msg_of_obj = []   # (header, sprite, is_trainer) per generated script line choice
    for h, info in plat.items():
        cname = man["maps"][h]["name"]
        suffix = cname.replace("MAP_APOC_SINNOH_", "")
        ev = info["events"]
        objects, warps = [], []
        warp_map = {}
        # Canalave: keep the return-ferry sailor (script 0 in the APOCSIN
        # bank) and station the HM porter next to him on the pier
        if h == "MAP_HEADER_CANALAVE_CITY":
            objects.append(OrderedDict([
                ("id", 200), ("spriteId", "SPRITE_SEAMAN"), ("movement", 0),
                ("type", 0), ("eventFlag", 0), ("scriptId", 1),
                ("facingDirection", 0), ("param0", 0), ("param1", 0), ("param2", 0),
                ("xRange", 0), ("yRange", 0), ("x", 38), ("z", 744), ("y", 0),
            ]))
            objects.append(OrderedDict([
                ("id", 201), ("spriteId", "SPRITE_DELIVERY"), ("movement", 0),
                ("type", 0), ("eventFlag", 0), ("scriptId", porter_script),
                ("facingDirection", 0), ("param0", 0), ("param1", 0), ("param2", 0),
                ("xRange", 0), ("yRange", 0), ("x", 40), ("z", 744), ("y", 0),
            ]))
        for o in ev["object_events"]:
            if str(o.get("flag", "0")) != "0":
                continue
            sprite = map_sprite(o["graphics_id"])
            if sprite is None:
                continue
            mv = convert_movement(o)
            if mv is None:
                continue
            movement, facing, xr, yr = mv
            is_trainer = o.get("trainer_type", "TRAINER_TYPE_NONE") != "TRAINER_TYPE_NONE"
            li = line_index_for(sprite, is_trainer, info["is_city"],
                                (o["x"] * 7 + o["z"] * 13) & 0xFFFF)
            objects.append(OrderedDict([
                ("id", len(objects)), ("spriteId", sprite), ("movement", movement),
                ("type", 0), ("eventFlag", 0), ("scriptId", li + 2),
                ("facingDirection", facing), ("param0", 0), ("param1", 0), ("param2", 0),
                ("xRange", xr), ("yRange", yr),
                ("x", o["x"]), ("z", o["z"]), ("y", 0),
            ]))
        for wi, w in enumerate(ev["warp_events"]):
            key = door_map.get((h, wi))
            if key is None or key not in interiors:
                continue
            warp_map[key] = len(warps)
            warps.append(OrderedDict([
                ("x", w["x"]), ("z", w["z"]),
                ("header", interiors[key]["cname"]), ("anchor", 0), ("y", 0),
            ]))
        if not objects and not warps:
            continue
        bgs = []
        sid = sign_scripts.get(h)
        if sid:
            for bg in ev.get("bg_events", []):
                bgs.append(OrderedDict([
                    ("scriptId", sid), ("type", 1),
                    ("x", bg["x"]), ("z", bg["z"]), ("y", 0), ("dir", 0),
                ]))
        if not objects and not warps and not bgs:
            continue
        fn = f"{OUTDOOR_ZE_BASE}_APOCSIN_{suffix}.json"
        result[h] = (fn, OrderedDict([
            ("header", "fielddata/script/scr_seq/event_EVERYWHERE.h"),
            ("bgs", bgs), ("objects", objects), ("warps", warps), ("coords", []),
        ]), warp_map)
    return result


def plan_interiors(man, plat):
    """One PC + one MART clone per city with such a door, plus a generic
    house clone for EVERY other door on town/city maps (so all buildings
    are enterable; each door gets its own header so the exit warp returns
    to the right spot)."""
    interiors = OrderedDict()
    nid = FIRST_INTERIOR_ID
    for h, info in plat.items():
        suffix = man["maps"][h]["name"].replace("MAP_APOC_SINNOH_", "")
        dests = [w["dest_header_id"] for w in info["events"]["warp_events"]]
        if any("POKECENTER" in d for d in dests):
            interiors[(h, "PC")] = {"id": nid, "cname": f"MAP_APOC_SIN_PC_{suffix}",
                                    "city": h, "kind": "PC"}
            nid += 1
        if any(("MART" in d or "SHOP" in d) for d in dests):
            interiors[(h, "MART")] = {"id": nid, "cname": f"MAP_APOC_SIN_MART_{suffix}",
                                      "city": h, "kind": "MART"}
            nid += 1
    door_map = {}   # (city_header, warp_index) -> interior key
    for h, info in plat.items():
        suffix = man["maps"][h]["name"].replace("MAP_APOC_SINNOH_", "")
        seen_pc = seen_mart = False
        for wi, w in enumerate(info["events"]["warp_events"]):
            d = w["dest_header_id"]
            if "POKECENTER" in d and not seen_pc and (h, "PC") in interiors:
                seen_pc = True
                door_map[(h, wi)] = (h, "PC")
                continue
            if ("MART" in d or "SHOP" in d) and not seen_mart and (h, "MART") in interiors:
                seen_mart = True
                door_map[(h, wi)] = (h, "MART")
                continue
            if not plat[h]["is_city"]:
                continue
            key = (h, "HOUSE", wi)
            interiors[key] = {
                "id": nid, "cname": f"MAP_APOC_SIN_H{wi:02d}_{suffix}",
                "city": h, "kind": "HOUSE", "warp_index": wi}
            door_map[(h, wi)] = key
            nid += 1
    return interiors, door_map


PC_DONOR_EVENTS = "066_T21PC0101.json"
MART_DONOR_EVENTS = "065_T21FS0101.json"
HOUSE_DONOR_EVENTS = "067_T21R0301.json"
PC_DONOR_HDR = "MAP_CHERRYGROVE_POKECENTER_1F"
MART_DONOR_HDR = "MAP_CHERRYGROVE_POKEMART"
HOUSE_DONOR_HDR = "MAP_CHERRYGROVE_SOUTHWEST_HOUSE"

# town sign slogans (route signs fall back to the plain name)
SLOGANS = {
    "TWINLEAF_TOWN": "Fresh and Free!",
    "SANDGEM_TOWN": "Town of Sand!",
    "JUBILIFE_CITY": "City of Joy!",
    "OREBURGH_CITY": "City of Energy!",
    "FLOAROMA_TOWN": "Vivid and Scented!",
    "ETERNA_CITY": "History Living!",
    "HEARTHOME_CITY": "Warm and Kind!",
    "SOLACEON_TOWN": "Free of Worry!",
    "VEILSTONE_CITY": "Hewn from Rock!",
    "PASTORIA_CITY": "Marsh Country!",
    "CELESTIC_TOWN": "Living History!",
    "CANALAVE_CITY": "The Cargo Port!",
    "SNOWPOINT_CITY": "City of Snow!",
    "SUNYSHORE_CITY": "Solar Powered!",
    "FIGHT_AREA": "The Battle Zone!",
    "SURVIVAL_AREA": "For Tough Trainers!",
    "RESORT_AREA": "For Relaxation!",
}


def display_name(suffix):
    return " ".join(w.capitalize() for w in suffix.split("_"))


# ---- location names (mapsec) ---------------------------------------------- #
# mapsec is an 8-bit header field; vanilla uses 0..234, leaving ~20 free
# values. Cities get individual names; routes/lakefronts share grouped ones.
MAPSEC_FIRST_NEW = 235
MAPSEC_CITIES = [
    "TWINLEAF_TOWN", "SANDGEM_TOWN", "JUBILIFE_CITY", "OREBURGH_CITY",
    "FLOAROMA_TOWN", "ETERNA_CITY", "HEARTHOME_CITY", "SOLACEON_TOWN",
    "VEILSTONE_CITY", "PASTORIA_CITY", "CELESTIC_TOWN", "CANALAVE_CITY",
    "SNOWPOINT_CITY", "SUNYSHORE_CITY", "POKEMON_LEAGUE",
]
MAPSEC_GROUPS = [("SINNOH_ROUTE", "Sinnoh Route"),
                 ("SINNOH_LAKEFRONT", "Sinnoh Lakefront"),
                 ("BATTLE_ZONE", "Battle Zone")]


def mapsec_plan(man):
    """suffix -> (constant name, display name); allocates the free 8-bit
    mapsec values. Returns (per_map, ordered [(const, display)])."""
    consts = []
    per_map = {}
    for c in MAPSEC_CITIES:
        consts.append((f"MAPSEC_APOC_{c}", display_name(c)))
    for gname, gdisp in MAPSEC_GROUPS:
        consts.append((f"MAPSEC_APOC_{gname}", gdisp))
    assert MAPSEC_FIRST_NEW + len(consts) <= 255
    for h, m in man["maps"].items():
        suffix = m["name"].replace("MAP_APOC_SINNOH_", "")
        if suffix in MAPSEC_CITIES:
            per_map[h] = f"MAPSEC_APOC_{suffix}"
        elif "LAKEFRONT" in suffix or "LAKE" in suffix:
            per_map[h] = "MAPSEC_APOC_SINNOH_LAKEFRONT"
        elif suffix in ("FIGHT_AREA", "SURVIVAL_AREA", "RESORT_AREA"):
            per_map[h] = "MAPSEC_APOC_BATTLE_ZONE"
        else:
            per_map[h] = "MAPSEC_APOC_SINNOH_ROUTE"
    return per_map, consts


def patch_mapsecs(consts):
    """Add MAPSEC constants + msg_0279 rows (indices 235+, regenerated)."""
    p = os.path.join(HG, "include/constants/map_sections.h")
    src = open(p).read()
    MB2 = "// APOC_SINNOH_LIFE MAPSEC BEGIN"
    ME2 = "// APOC_SINNOH_LIFE MAPSEC END"
    lines = [MB2]
    for i, (cname, _) in enumerate(consts):
        lines.append(f"#define {cname:<40} {MAPSEC_FIRST_NEW + i}")
    lines.append(ME2)
    block = "\n".join(lines)
    if MB2 in src:
        src = src[:src.find(MB2)] + block + src[src.find(ME2) + len(ME2):]
    else:
        anchor = re.search(r"#define MAPSEC_\w+\s+234\n", src)
        assert anchor, "mapsec 234 not found"
        i = anchor.end()
        src = src[:i] + "\n" + block + "\n" + src[i:]
    open(p, "w").write(src)

    gp = os.path.join(HG, "files/msgdata/msg/msg_0279.gmm")
    src = open(gp).read()
    # drop any rows with index >= 235 (previous runs), then append ours
    src = re.sub(r"\t<row [^>]*index=\"(2[4-9][0-9]|23[5-9]|[3-9][0-9][0-9])\".*?</row>\n",
                 "", src, flags=re.S)
    rows = []
    for i, (_, disp) in enumerate(consts):
        idx = MAPSEC_FIRST_NEW + i
        rows.append(
            f'\t<row id="msg_0279_{idx:05d}" index="{idx}">\n'
            f'\t\t<attribute name="window_context_name">used</attribute>\n'
            f'\t\t<language name="English">{disp}</language>\n'
            f"\t</row>\n")
    src = src.replace("</body>", "".join(rows) + "</body>")
    open(gp, "w").write(src)


# ---- music ----------------------------------------------------------------- #
BIG_CITIES = {"JUBILIFE_CITY", "HEARTHOME_CITY", "VEILSTONE_CITY"}
PORT_CITIES = {"CANALAVE_CITY", "SUNYSHORE_CITY", "PASTORIA_CITY"}


def music_for(suffix, is_city):
    if suffix == "SNOWPOINT_CITY":
        return "SEQ_GS_C_FUSUBE"
    if suffix in BIG_CITIES:
        return "SEQ_GS_C_KOGANE"
    if suffix in PORT_CITIES:
        return "SEQ_GS_C_ASAGI"
    if suffix.endswith("_TOWN") or suffix in ("FIGHT_AREA", "SURVIVAL_AREA",
                                              "RESORT_AREA"):
        return "SEQ_GS_T_WAKABA"
    if is_city:
        return "SEQ_GS_C_KIKYOU"
    pool = ["SEQ_GS_R_1_29", "SEQ_GS_R_2_30", "SEQ_GS_R_4_34", "SEQ_GS_R_7_42"]
    return pool[sum(map(ord, suffix)) % len(pool)]


def build_interior_events(interiors, outdoor, man):
    """Clone donor events; retarget the exit warp; drop other warps."""
    donors = {"PC": json.load(open(os.path.join(ZE_DIR, PC_DONOR_EVENTS))),
              "MART": json.load(open(os.path.join(ZE_DIR, MART_DONOR_EVENTS))),
              "HOUSE": json.load(open(os.path.join(ZE_DIR, HOUSE_DONOR_EVENTS)))}
    files = {}
    for i, (key, info) in enumerate(interiors.items()):
        d = json.loads(json.dumps(donors[info["kind"]]))  # deep copy
        city_h = info["city"]
        city_cname = man["maps"][city_h]["name"]
        anchor = 0
        if city_h in outdoor:
            anchor = outdoor[city_h][2].get(key, 0)
        warps = [w for w in d.get("warps", []) if w["header"] == "MAP_CHERRYGROVE"]
        assert warps, f"donor {info['kind']} has no exit warp"
        for w in warps:
            w["header"] = city_cname
            w["anchor"] = anchor
        d["warps"] = warps
        suffix = info["cname"].replace("MAP_APOC_SIN_", "")
        fn = f"{INTERIOR_ZE_BASE + i}_APOCSIN_{suffix}.json"
        files[key] = (fn, d)
    return files


# ---- scr_seq + msg --------------------------------------------------------- #

def write_scripts(man):
    """msg bank + script bank. Script indices:
       0                 = Canalave->Cherrygrove return ferry
       1..len(LINES)     = generic townsfolk dialogue
       next              = HM porter (gives HM01-08)
       then one sign script per map with sign text.
    Returns {header_name: sign scriptId (events 1-based)} and the porter
    scriptId."""
    msgs = [text for _, text in LINES]
    PORTER_MSG0 = len(msgs)
    msgs.append("Ahoy! You look like an explorer.\\nTake these--the full set of\\fHIDDEN MACHINES!\\rUse them from the bag: the field\\nmoves work as long as you carry them.")
    msgs.append("Got your HMs already!\\nGo see the world, trainer.")
    sign_map = {}   # header -> script index (0-based)
    sign_texts = []
    for h, m in man["maps"].items():
        suffix = m["name"].replace("MAP_APOC_SINNOH_", "")
        name = display_name(suffix)
        slogan = SLOGANS.get(suffix)
        text = f"{name}\\n“{slogan}”" if slogan else name
        sign_map[h] = len(sign_texts)
        sign_texts.append(text)
    SIGN_MSG0 = len(msgs)
    msgs.extend(sign_texts)

    lines_gmm = []
    for i, text in enumerate(msgs):
        lines_gmm.append(
            f'\t<row id="msg_0830_APOCSIN_{i:05d}" index="{i}">\n'
            f'\t\t<attribute name="window_context_name">used</attribute>\n'
            f'\t\t<language name="English">{text}</language>\n'
            f"\t</row>")
    gmm = ('<?xml version="1.0"?>\n<body language="English">\n'
           + "\n".join(lines_gmm) + "\n</body>\n")
    with open(os.path.join(HG, "files/msgdata/msg/msg_0830_APOCSIN.gmm"), "w") as f:
        f.write(gmm)

    nscripts_before_signs = 1 + len(LINES) + 1   # ferry + lines + porter
    PORTER_SCRIPT = 1 + len(LINES)
    total = nscripts_before_signs + len(sign_texts)
    s = ['#include "constants/scrcmd.h"',
         '#include "msgdata/msg/msg_0830_APOCSIN.h"',
         '\t.include "asm/macros/script.inc"', "", "\t.rodata", "",
         "; ===== APOCRYPHA: shared script bank for the ported Sinnoh region.",
         "; 0 = Canalave->Cherrygrove return ferry; 1..N generic dialogue;",
         "; then the HM porter, then one town/route sign per map. =====",
         ]
    for i in range(total):
        s.append(f"\tscrdef scr_seq_APOCSIN_{i:03d}")
    s.append("\tscrdef_end")
    s.append("")
    s.append("scr_seq_APOCSIN_000:")
    s.append("\tplay_se SEQ_SE_DP_SELECT")
    s.append("\tlockall")
    s.append("\tfaceplayer")
    s.append("\tfade_screen 6, 1, 0, RGB_BLACK")
    s.append("\twait_fade")
    s.append("\twarp MAP_CHERRYGROVE, 0, 559, 409, DIR_WEST")
    s.append("\tfade_screen 6, 1, 1, RGB_BLACK")
    s.append("\twait_fade")
    s.append("\treleaseall")
    s.append("\tend")
    s.append("")
    for i in range(len(LINES)):
        s.append(f"scr_seq_APOCSIN_{i + 1:03d}:")
        s.append(f"\tsimple_npc_msg msg_0830_APOCSIN_{i:05d}")
        s.append("\tend")
        s.append("")
    # HM porter: gives HM01..HM08 once (keyed on owning HM01)
    s.append(f"scr_seq_APOCSIN_{PORTER_SCRIPT:03d}:")
    s.append("\tplay_se SEQ_SE_DP_SELECT")
    s.append("\tlockall")
    s.append("\tfaceplayer")
    s.append("\thasitem ITEM_HM01, 1, VAR_SPECIAL_RESULT")
    s.append("\tcompare VAR_SPECIAL_RESULT, 1")
    s.append(f"\tgoto_if_eq _PORTER_DONE")
    s.append(f"\tnpc_msg msg_0830_APOCSIN_{PORTER_MSG0:05d}")
    for hm in range(1, 9):
        s.append(f"\tgiveitem_no_check ITEM_HM{hm:02d}, 1")
    s.append("\twait_button_or_walk_away")
    s.append("\tclosemsg")
    s.append("\treleaseall")
    s.append("\tend")
    s.append("_PORTER_DONE:")
    s.append(f"\tnpc_msg msg_0830_APOCSIN_{PORTER_MSG0 + 1:05d}")
    s.append("\twait_button_or_walk_away")
    s.append("\tclosemsg")
    s.append("\treleaseall")
    s.append("\tend")
    s.append("")
    for i in range(len(sign_texts)):
        idx = nscripts_before_signs + i
        s.append(f"scr_seq_APOCSIN_{idx:03d}:")
        s.append("\tplay_se SEQ_SE_DP_SELECT")
        s.append("\tlockall")
        s.append(f"\tnpc_msg msg_0830_APOCSIN_{SIGN_MSG0 + i:05d}")
        s.append("\twait_button_or_walk_away")
        s.append("\tclosemsg")
        s.append("\treleaseall")
        s.append("\tend")
        s.append("")
    s.append("\t.balign 4, 0")
    with open(os.path.join(HG, "files/fielddata/script/scr_seq/scr_seq_0967_APOCSIN.s"), "w") as f:
        f.write("\n".join(s) + "\n")
    sign_scripts = {h: nscripts_before_signs + i + 1 for h, i in sign_map.items()}
    return sign_scripts, PORTER_SCRIPT + 1


# ---- encounters ------------------------------------------------------------ #

def enc_row(cols, label, enc):
    row = {}
    for c in cols:
        row[c] = "SPECIES_NONE" if "species" in c or c in (
            "hoenn1", "hoenn2", "sinnoh1", "sinnoh2") or c.startswith("swarm") else "0"
    row["mapname"] = label
    land = enc.get("land_encounters") or []
    if len(land) == 12:
        row["rate_walk"] = str(enc.get("land_rate", 0))
        for i, e in enumerate(land):
            row[f"land_lvl{i}"] = str(e["level"])
            for tod in ("morn", "day", "nite"):
                row[f"land_species_{tod}{i}"] = e["species"]
        morning, night = enc.get("morning") or [], enc.get("night") or []
        for j, sp in enumerate(morning[:2]):
            row[f"land_species_morn{j + 2}"] = sp
        for j, sp in enumerate(night[:2]):
            row[f"land_species_nite{j + 2}"] = sp
        ruby, sapp = enc.get("ruby") or [], enc.get("sapphire") or []
        if ruby:
            row["hoenn1"] = ruby[0]
        if sapp:
            row["hoenn2"] = sapp[0]
        radar = enc.get("radar") or []
        if len(radar) >= 2:
            row["sinnoh1"], row["sinnoh2"] = radar[0], radar[1]
        swarms = enc.get("swarms") or []
        if len(swarms) >= 2:
            row["swarm_species0"], row["swarm_species1"] = swarms[0], swarms[1]
            row["swarm_species2"] = row["swarm_species3"] = land[0]["species"]
    for kind, csvk in (("surf", "surf"), ("old_rod", "oldrod"),
                       ("good_rod", "goodrod"), ("super_rod", "superrod")):
        slots = enc.get(f"{kind}_encounters") or []
        rate = enc.get(f"{kind}_rate", 0)
        if slots:
            row[f"rate_{csvk}"] = str(rate)
            for i, e in enumerate(slots[:5]):
                row[f"lvl_min_{csvk}{i}"] = str(e["level_min"])
                row[f"lvl_max_{csvk}{i}"] = str(e["level_max"])
                row[f"species_{csvk}{i}"] = e["species"]
    return row


def append_encounters(man, plat):
    """Append one row per Sinnoh map with encounter data to BOTH csvs.
    Returns {header_name: bank_index}."""
    banks = {}
    for game in ("g", "s"):
        path = os.path.join(HG, f"files/fielddata/encountdata/{game}_enc_data.csv")
        lines = [l.rstrip("\n") for l in open(path)]
        cols = lines[0].split(",")
        kept = [l for l in lines[1:] if l.strip() and not l.startswith("APOCSIN_")]
        rows = []
        for h, info in plat.items():
            if not info["enc"]:
                continue
            label = "APOCSIN_" + man["maps"][h]["name"].replace("MAP_APOC_SINNOH_", "")
            r = enc_row(cols, label, info["enc"])
            if r["rate_walk"] == "0" and r["rate_surf"] == "0":
                continue
            rows.append((h, ",".join(r[c] for c in cols)))
        for i, (h, _) in enumerate(rows):
            banks[h] = len(kept) + i
        with open(path, "w") as f:
            f.write("\n".join([lines[0]] + kept + [r for _, r in rows]) + "\n")
    return banks


# ---- header patching ------------------------------------------------------- #

def patch_sinnoh_block(man, outdoor, enc_banks, mapsecs, plat):
    path = os.path.join(HG, "src/data/map_headers.h")
    src = open(path).read()
    for h, m in man["maps"].items():
        cname = m["name"]
        suffix = cname.replace("MAP_APOC_SINNOH_", "")
        i = src.find("[" + cname + "]")
        assert i > 0, cname
        j = src.find("}", i)
        seg = src[i:j]
        def setf(seg, field, val):
            return re.sub(r"(\." + field + r"\s*=\s*)[^,\n]+", r"\g<1>" + val, seg)
        seg = setf(seg, "scriptsBank", "NARC_scr_seq_scr_seq_0967_APOCSIN_bin")
        seg = setf(seg, "msgBank", "NARC_msg_msg_0830_APOCSIN_bin")
        seg = setf(seg, "mapsec", mapsecs[h])
        music = music_for(suffix, plat[h]["is_city"])
        seg = setf(seg, "dayMusicId", music)
        seg = setf(seg, "nightMusicId", music)
        if h in outdoor:
            fn = outdoor[h][0].replace(".json", "")
            seg = setf(seg, "eventsBank", f"NARC_zone_event_{fn}_bin")
        if h in enc_banks:
            seg = setf(seg, "wildEncounterBank", str(enc_banks[h]))
        src = src[:i] + seg + src[j:]
    open(path, "w").write(src)


def interior_header_entry(info, donor_entry):
    """Clone the donor header entry text with our events bank + mapsec."""
    seg = donor_entry
    def setf(seg, field, val):
        return re.sub(r"(\." + field + r"\s*=\s*)[^,\n]+", r"\g<1>" + val, seg)
    seg = setf(seg, "eventsBank", f"NARC_zone_event_{info['zefile']}_bin")
    seg = setf(seg, "mapsec", "MAPSEC_MYSTERY_ZONE")
    seg = setf(seg, "outgoingCalls", "FALSE")
    seg = setf(seg, "incomingCalls", "FALSE")
    seg = setf(seg, "radioSignal", "FALSE")
    return f"    [{info['cname']}] = " + seg + ","


def patch_interior_headers(interiors, interior_files):
    hdr_path = os.path.join(HG, "src/data/map_headers.h")
    src = open(hdr_path).read()
    donors = {}
    for kind, donor in (("PC", PC_DONOR_HDR), ("MART", MART_DONOR_HDR),
                        ("HOUSE", HOUSE_DONOR_HDR)):
        i = src.find("[" + donor + "]")
        j = src.find("},", i)
        donors[kind] = src[src.find("{", i):j + 1]
    entries = [MARK_BEGIN]
    for key, info in interiors.items():
        info["zefile"] = interior_files[key][0].replace(".json", "")
        entries.append(interior_header_entry(info, donors[info["kind"]]))
    entries.append(MARK_END)
    block = "\n".join(entries)
    if MARK_BEGIN in src:
        pre = src[:src.find(MARK_BEGIN)]
        post = src[src.find(MARK_END) + len(MARK_END):]
        src = pre + block + post
    else:
        # insert before the closing of the header array: after HOENN END block
        anchor = "// APOC_REGIONPORT HOENN END"
        i = src.find(anchor)
        assert i > 0
        i += len(anchor)
        src = src[:i] + "\n" + block + src[i:]
    open(hdr_path, "w").write(src)

    maps_path = os.path.join(HG, "include/constants/maps.h")
    src = open(maps_path).read()
    defines = [MARK_BEGIN]
    for key, info in interiors.items():
        defines.append(f"#define {info['cname']:<49} {info['id']}")
    defines.append(MARK_END)
    block = "\n".join(defines)
    if MARK_BEGIN in src:
        pre = src[:src.find(MARK_BEGIN)]
        post = src[src.find(MARK_END) + len(MARK_END):]
        src = pre + block + post
    else:
        anchor = "// APOC_REGIONPORT HOENN END"
        i = src.find(anchor)
        assert i > 0
        i += len(anchor)
        src = src[:i] + "\n\n" + block + src[i:]
    open(maps_path, "w").write(src)


def main():
    man = json.load(open(os.path.join(OUT, "sinnoh_manifest.json")))
    print("loading platinum events/encounters...")
    plat = load_platinum(man)

    interiors, door_map = plan_interiors(man, plat)
    sign_scripts, porter_script = write_scripts(man)
    outdoor = build_outdoor_events(man, plat, interiors, door_map, sign_scripts,
                                   porter_script)
    interior_files = build_interior_events(interiors, outdoor, man)

    # clean previous generated zone_event files
    for f in os.listdir(ZE_DIR):
        if re.match(r"^\d{3}_APOCSIN_.*\.json$", f):
            os.remove(os.path.join(ZE_DIR, f))
    nobj = nwarp = 0
    for h, (fn, d, _) in outdoor.items():
        with open(os.path.join(ZE_DIR, fn), "w") as f:
            json.dump(d, f, indent=2)
        nobj += len(d["objects"]); nwarp += len(d["warps"])
    for key, (fn, d) in interior_files.items():
        with open(os.path.join(ZE_DIR, fn), "w") as f:
            json.dump(d, f, indent=2)
    print(f"zone events: {len(outdoor)} outdoor files ({nobj} NPCs, {nwarp} warps), "
          f"{len(interior_files)} interior clones")

    enc_banks = append_encounters(man, plat)
    print(f"encounters: {len(enc_banks)} maps")

    mapsecs, consts = mapsec_plan(man)
    patch_mapsecs(consts)
    patch_sinnoh_block(man, outdoor, enc_banks, mapsecs, plat)
    patch_interior_headers(interiors, interior_files)

    overrides = {}
    for h, m in man["maps"].items():
        suffix = m["name"].replace("MAP_APOC_SINNOH_", "")
        music = music_for(suffix, plat[h]["is_city"])
        ov = {"scriptsBank": "NARC_scr_seq_scr_seq_0967_APOCSIN_bin",
              "msgBank": "NARC_msg_msg_0830_APOCSIN_bin",
              "mapsec": mapsecs[h],
              "dayMusicId": music, "nightMusicId": music}
        if h in outdoor:
            ov["eventsBank"] = f"NARC_zone_event_{outdoor[h][0].replace('.json', '')}_bin"
        if h in enc_banks:
            ov["wildEncounterBank"] = str(enc_banks[h])
        overrides[h] = ov
    with open(os.path.join(OUT, "sinnoh_overrides.json"), "w") as f:
        json.dump(overrides, f, indent=1)
    print("done; header patches applied, overrides saved")


if __name__ == "__main__":
    main()
